=== PolanieOnLine/PolanieOnLine/data/conf/creatures.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="stendhal" xmlns:tns="http://www.example.org/creatures"
	elementFormDefault="qualified" xmlns:Q2="stendhal">

	<xsd:element name="creatures" type="Q2:CreaturesType"></xsd:element>

	<xsd:complexType name="CreaturesType">
		<xsd:sequence>
			<xsd:element name="creature" type="Q2:CreatureType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="CreatureType">
		<xsd:sequence>
			<xsd:element name="type" type="Q2:Type" minOccurs="1" />
			<xsd:element name="hidden" type="xsd:string" minOccurs="0" />
			<xsd:element name="description" type="xsd:string" minOccurs="0" />
			<xsd:element name="attributes" type="Q2:Attributes" minOccurs="1" />
			<xsd:element name="level" type="Q2:Level" minOccurs="1" />
			<xsd:element name="experience" type="Q2:Experience"	minOccurs="1" />
			<xsd:element name="respawn" type="Q2:Respawn" />
			<xsd:element name="blood" type="Q2:Blood" minOccurs="0" />
			<xsd:element name="corpse" type="Q2:Corpse" />
			<xsd:element name="drops" type="Q2:Drops" minOccurs="0" />
			<xsd:element name="slots" type="Q2:Slots" minOccurs="0" />
			<xsd:element name="equips" type="Q2:Equips" minOccurs="0" />
			<xsd:element name="abilities" type="Q2:Abilities" minOccurs="0"/>
			<xsd:element name="ai" type="Q2:Ai" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="condition" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="quantity" type="xsd:string" />
		<xsd:attribute name="probability" type="xsd:double" />
	</xsd:complexType>

	<xsd:complexType name="SpecialItem">
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Q2:Item" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="special" type="Q2:SpecialItem" minOccurs="0"
        		maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Respawn">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="value" type="xsd:positiveInteger"/>
	</xsd:complexType>

	<xsd:complexType name="Blood">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Corpse">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="width" type="xsd:positiveInteger"/>
		<xsd:attribute name="height" type="xsd:positiveInteger"/>
		<xsd:attribute name="harmless" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ratk" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="armor_type" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" use="required">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:enumeration value="none" />
								<xsd:enumeration value="light" />
								<xsd:enumeration value="medium" />
								<xsd:enumeration value="heavy" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="armor_hp" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:nonNegativeInteger" use="required" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="resistance" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="visibility" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="state" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Q2:Says" minOccurs="0" />
			<xsd:element name="profile" type="Q2:Profile" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Q2:Text" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="text" type="Q2:Text" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="sound" type="Q2:Sound" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="movement" type="Q2:Movement" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="death" type="Q2:Death" minOccurs="0"
				maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Text">
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="state" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Sound">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Movement">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="Death">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="params" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string" />
		<xsd:attribute name="subclass" type="xsd:string" />
		<xsd:attribute name="shadow" type="xsd:string" />
		<xsd:attribute name="tileid" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer" />
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer" />
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="slot" type="Q2:Slot" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Abilities">
		<xsd:sequence>
			<xsd:element name="damage" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" default="cut"/>
					<xsd:attribute name="rangedType" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="susceptibility" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="statusattack" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Slot">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="item" type="xsd:string" use="required" />
		<xsd:attribute name="quantity" type="xsd:positiveInteger" />
	</xsd:complexType>
	
</xsd:schema>

=== PolanieOnLine/PolanieOnLine/data/conf/creatures/pol/human_knights.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<creature name="rycerz szafirowy">
		<type class="human" subclass="rycerz_blekitny" tileid="pol_rycerze.png:0"/>
		<description/>
		<attributes>
			<atk value="556"/>
			<def value="88"/>
			<armor value="heavy"/>
			<hp value="500"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="74"/>
		<experience value="5500"/>
		<respawn value="3000"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[20,50]" probability="100.0"/>
			<item value="szafir" quantity="[1,1]" probability="0.008"/>
			<item value="lazurowy płaszcz smoczy" quantity="[1,1]" probability="10.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="bleeding_attack" params="2"/>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="rycerz karmazynowy">
		<type class="human" subclass="rycerz_karmazynowy" tileid="pol_rycerze.png:1"/>
		<description/>
		<attributes>
			<atk value="576"/>
			<def value="88"/>
			<armor value="heavy"/>
			<hp value="500"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="77"/>
		<experience value="6000"/>
		<respawn value="3000"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[10,60]" probability="100.0"/>
			<item value="rubin" quantity="[1,1]" probability="0.008"/>
			<item value="karmazynowy płaszcz smoczy" quantity="[1,1]" probability="20.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="bleeding_attack" params="2"/>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="rycerz szmaragdowy">
		<type class="human" subclass="rycerz_szmaragdowy" tileid="pol_rycerze.png:2"/>
		<description/>
		<attributes>
			<atk value="536"/>
			<def value="88"/>
			<armor value="heavy"/>
			<hp value="500"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="72"/>
		<experience value="5100"/>
		<respawn value="3000"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[5,60]" probability="100.0"/>
			<item value="szmaragd" quantity="[1,1]" probability="0.008"/>
			<item value="szmaragdowy płaszcz smoczy" quantity="[1,1]" probability="20.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="bleeding_attack" params="2"/>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="rycerz w złotej zbroi">
		<type class="human" subclass="rycerz_zloty" tileid="pol_rycerze.png:3"/>
		<description/>
		<attributes>
			<atk value="616"/>
			<def value="88"/>
			<armor value="heavy"/>
			<hp value="500"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="81"/>
		<experience value="6600"/>
		<respawn value="3000"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[10,110]" probability="100.0"/>
			<item value="sztabka złota" quantity="[1,1]" probability="0.001"/>
			<item value="złoty płaszcz" quantity="[1,1]" probability="2.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="czarny rycerz">
		<type class="human" subclass="czarny_rycerz" tileid="pol_rycerze.png:4"/>
		<description/>
		<attributes>
			<atk value="600"/>
			<def value="40"/>
			<armor value="heavy"/>
			<hp value="800"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="102"/>
		<experience value="6420"/>
		<respawn value="3020"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[4,40]" probability="100.0"/>
			<item value="czarna zbroja" quantity="[1,1]" probability="0.005"/>
			<item value="czarne buty" quantity="[1,1]" probability="0.2"/>
			<item value="czarny hełm" quantity="[1,1]" probability="0.25"/>
			<item value="czarny sztylet" quantity="[1,1]" probability="0.025"/>
			<item value="czarny pas" quantity="[1,1]" probability="0.05"/>
		</drops>
		<equips/>
		<ai>
			<profile name="bleeding_attack" params="2"/>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
			<profile name="patrolling"/>
			<profile name="boss"/>
		</ai>
	</creature>

	<creature name="strażnik">
		<type class="human" subclass="straznik" tileid="pol_rycerze.png:5"/>
		<description/>
		<attributes>
			<atk value="400"/>
			<def value="70"/>
			<armor value="medium"/>
			<hp value="800"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="92"/>
		<experience value="6820"/>
		<respawn value="3020"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[2,30]" probability="100.0"/>
			<item value="polska tarcza drewniana" quantity="[1,1]" probability="5.0"/>
			<item value="buty żelazne" quantity="[1,1]" probability="2.0"/>
			<item value="hełm kolczy" quantity="[1,1]" probability="5.0"/>
			<item value="półtorak" quantity="[1,1]" probability="5.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="bleeding_attack" params="2"/>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="strażnik grobli">
		<type class="human" subclass="straznik_grobli" tileid="pol_rycerze.png:6"/>
		<description/>
		<attributes>
			<atk value="475"/>
			<def value="76"/>
			<armor value="medium"/>
			<hp value="800"/>
			<speed value="0.7"/>
			<size value="1,1"/>
		</attributes>
		<level value="102"/>
		<experience value="9320"/>
		<respawn value="4020"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[1,55]" probability="100.0"/>
			<item value="polska tarcza drewniana" quantity="[1,1]" probability="5.0"/>
			<item value="buty żelazne" quantity="[1,1]" probability="2.0"/>
			<item value="hełm kolczy" quantity="[1,1]" probability="5.0"/>
			<item value="półtorak" quantity="[1,1]" probability="5.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="bleeding_attack" params="2"/>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="strażnik bramy">
		<type class="human" subclass="straznik_bramy" tileid="pol_rycerze.png:7"/>
		<description/>
		<attributes>
			<atk value="550"/>
			<def value="77"/>
			<armor value="medium"/>
			<hp value="1100"/>
			<speed value="0.6"/>
			<size value="1,1"/>
		</attributes>
		<level value="122"/>
		<experience value="11420"/>
		<respawn value="3020"/>
		<corpse name="human"/>
		<drops>
			<item value="money" quantity="[2,61]" probability="100.0"/>
			<item value="polska tarcza drewniana" quantity="[1,1]" probability="10.0"/>
			<item value="buty żelazne" quantity="[1,1]" probability="2.0"/>
			<item value="hełm kolczy" quantity="[1,1]" probability="7.0"/>
			<item value="półtorak" quantity="[1,1]" probability="5.0"/>
		</drops>
		<equips/>
		<ai>
			<profile name="bleeding_attack" params="2"/>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="rycerz na białym koniu">
		<type class="human" subclass="straznik_na_koniu" tileid="pol_rycerze.png:8"/>
		<description/>
		<attributes>
			<atk value="1374"/>
			<def value="90"/>
			<armor value="heavy"/>
			<hp value="2800"/>
			<speed value="1.0"/>
			<size value="2,2"/>
		</attributes>
		<level value="202"/>
		<experience value="71420"/>
		<respawn value="3020"/>
		<corpse name="huge_animalhuman"/>
		<drops>
			<item value="money" quantity="[20,220]" probability="90.0"/>
			<item value="mięso" quantity="[1,2]" probability="80.0"/>
			<item value="buty żelazne" quantity="[1,1]" probability="3.0"/>
			<item value="hełm kolczy" quantity="[1,1]" probability="7.0"/>
			<item value="magiczne spodnie płytowe" quantity="[1,1]" probability="1.0"/>
			<item value="czarna halabarda" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips/>
		<ai>
			<profile name="bleeding_attack" params="5"/>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
			<profile name="attack weakest"/>
			<profile name="boss"/>
		</ai>
	</creature>
</creatures>

=== PolanieOnLine/PolanieOnLine/data/conf/creatures/pol/immortal.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: niesmiertelne -->
	<creature name="mgła">
		<type class="immortal" subclass="mgla" tileid="pol_niesmiertelne.png:0"/>
		<description>Mgła spowiła pobliskie otoczenie, musisz uważać na zjawy i inne upióry!</description>
		<attributes>
			<atk value="99"/>
			<def value="1"/>
			<hp value="1"/>
			<speed value="0.1"/>
			<size value="1,1"/>
			<resistance value="25"/>
			<visibility value="50"/>
		</attributes>
		<level value="0"/>
		<experience value="1"/>
		<respawn value="999"/>
		<corpse name="fly"/>
		<drops>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
			<profile name="active_idle"/>
			<profile name="flying"/>
			<profile name="immortal"/>
		</ai>
	</creature>

	<creature name="trujące opary">
		<type class="immortal" subclass="trujace_opary" tileid="pol_niesmiertelne.png:1"/>
		<attributes>
			<atk value="199"/>
			<def value="1"/>
			<hp value="1"/>
			<speed value="0.1"/>
			<size value="1,1"/>
			<resistance value="25"/>
			<visibility value="50"/>
		</attributes>
		<level value="0"/>
		<experience value="1"/>
		<respawn value="999"/>
		<corpse name="fly"/>
		<drops>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="poisonous" params="40,mocna trucizna"/>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="attack weakest"/>
			<profile name="active_idle"/>
			<profile name="flying"/>
			<profile name="immortal"/>
		</ai>
	</creature>

	<creature name="trąba powietrzna">
		<type class="immortal" subclass="tornado" tileid="pol_niesmiertelne.png:2"/>
		<description>Oto trąba powietrzna. Pędź ile w sił w nogach, tornado gnie w tą samą stronę co ty!</description>
		<attributes>
			<atk value="20000"/>
			<def value="1"/>
			<hp value="1"/>
			<speed value="1.0"/>
			<size value="2,2"/>
			<resistance value="50"/>
			<visibility value="75"/>
		</attributes>
		<level value="800"/>
		<experience value="1"/>
		<respawn value="999"/>
		<corpse name="fly"/>
		<drops>
		</drops>
		<equips>
			<slot name="lhand" item="tarcza z mithrilu" quantity="1"/>
			<slot name="rhand" item="szczerbiec" quantity="1"/>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
			<profile name="lifesteal" params="0.1"/>
			<profile name="patrolling"/>
			<profile name="active_idle"/>
			<profile name="flying"/>
			<profile name="immortal"/>
		</ai>
	</creature>

	<creature name="trąba wodna">
		<type class="immortal" subclass="tornado_wodne" tileid="pol_niesmiertelne.png:3"/>
		<attributes>
			<atk value="20000"/>
			<def value="1"/>
			<hp value="1"/>
			<speed value="1.0"/>
			<size value="2,2"/>
			<resistance value="50"/>
			<visibility value="75"/>
		</attributes>
		<level value="800"/>
		<experience value="1"/>
		<respawn value="999"/>
		<corpse name="fly"/>
		<drops>
		</drops>
		<equips>
			<slot name="lhand" item="tarcza z mithrilu" quantity="1"/>
			<slot name="rhand" item="szczerbiec" quantity="1"/>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
			<profile name="lifesteal" params="0.1"/>
			<profile name="attack weakest"/>
			<profile name="active_idle"/>
			<profile name="flying"/>
			<profile name="immortal"/>
		</ai>
	</creature>
	<!-- END: niesmiertelne -->
</creatures>

=== PolanieOnLine/PolanieOnLine/data/conf/creatures/stendhal/human_barbarian.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<creature name="barbarzyńca">
		<type class="human" subclass="barbarian" tileid="human_barbarian.png:3"/>
		<description></description>
		<attributes>
			<atk value="350"/>
			<def value="57"/>
			<armor_type value="medium"/>
			<hp value="258"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="40"/>
		<experience value="1886"/>
		<respawn value="1520"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[10,20]" probability="100.0"/>
			<item value="zbroja barbarzyńcy" quantity="[1,1]" probability="0.5"/>
			<item value="rękawice barbarzyńcy" quantity="[1,1]" probability="0.5"/>
			<item value="złota zbroja" quantity="[1,1]" probability="0.05"/>
			<item value="złoty pas" quantity="[1,1]" probability="0.4"/>
			<item value="złoty pyrlik" quantity="[1,1]" probability="1.0"/>
			<item value="tarcza z czaszką" quantity="[1,1]" probability="0.5"/>
			<item value="nóż z kości" quantity="[1,1]" probability="10.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="barbarzyńca wilczur">
		<type class="human" subclass="barbarian_wolf" tileid="human_barbarian.png:5"/>
		<description></description>
		<attributes>
			<atk value="365"/>
			<def value="62"/>
			<armor_type value="medium"/>
			<hp value="292"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="44"/>
		<experience value="2194"/>
		<respawn value="1600"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[10,30]" probability="100.0"/>
			<item value="butelka wody" quantity="[1,2]" probability="30.0"/>
			<item value="zbroja barbarzyńcy" quantity="[1,1]" probability="2.5"/>
			<item value="złota zbroja" quantity="[1,1]" probability="0.25"/>
			<item value="pas barbarzyńcy" quantity="[1,1]" probability="0.5"/>
			<item value="złoty pas" quantity="[1,1]" probability="1.0"/>
			<item value="młot bojowy" quantity="[1,1]" probability="1.0"/>
			<item value="złoty hełm" quantity="[1,1]" probability="0.5"/>
			<item value="hełm barbarzyńcy" quantity="[1,1]" probability="12.5"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="barbarzyńca elitarny">
		<type class="human" subclass="barbarian_elite" tileid="human_barbarian.png:1"/>
		<description></description>
		<attributes>
			<atk value="413"/>
			<def value="67"/>
			<armor_type value="medium"/>
			<hp value="330"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="48"/>
		<experience value="2670"/>
		<respawn value="1600"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[10,50]" probability="100.0"/>
			<item value="butelka wody" quantity="[1,2]" probability="30.0"/>
			<item value="zbroja barbarzyńcy" quantity="[1,1]" probability="5.0"/>
			<item value="złota zbroja" quantity="[1,1]" probability="0.5"/>
			<item value="złote buty" quantity="[1,1]" probability="1.0"/>
			<item value="złoty pas" quantity="[1,1]" probability="0.3"/>
			<item value="młot bojowy" quantity="[1,1]" probability="1.0"/>
			<item value="młot chaosu" quantity="[1,1]" probability="0.0050"/>
			<item value="złota tarcza" quantity="[1,1]" probability="0.05"/>
			<item value="spodnie barbarzyńcy" quantity="[1,1]" probability="7.5"/>
			<item value="pas barbarzyńcy" quantity="[1,1]" probability="0.5"/>
			<item value="tarcza barbarzyńcy" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="barbarzyńca kapłan">
		<type class="human" subclass="barbarian_priest" tileid="human_barbarian.png:4"/>
		<description></description>
		<attributes>
			<atk value="425"/>
			<def value="68"/>
			<armor_type value="light"/>
			<hp value="380"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="53"/>
		<experience value="3027"/>
		<respawn value="1650"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[10,50]" probability="100.0"/>
			<item value="butelka wody" quantity="[1,2]" probability="30.0"/>
			<item value="zbroja szamana barbarzyńców" quantity="[1,1]" probability="1.0"/>
			<item value="rękawice barbarzyńcy" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips>
		</equips>
		<abilities>
			<damage type="light"/>
			<susceptibility type="dark" value="1.2"/>
			<susceptibility type="light" value="0.7"/>
		</abilities>
		<ai>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="barbarzyńca szaman">
		<type class="human" subclass="barbarian_chaman" tileid="human_barbarian.png:0"/>
		<description></description>
		<attributes>
			<atk value="449"/>
			<def value="67"/>
			<armor_type value="light"/>
			<hp value="435"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="58"/>
		<experience value="3435"/>
		<respawn value="1720"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[10,50]" probability="100.0"/>
			<item value="butelka wody" quantity="[1,2]" probability="30.0"/>
			<item value="złoty hełm wikingów" quantity="[1,1]" probability="0.25"/>
			<item value="zbroja szamana barbarzyńców" quantity="[1,1]" probability="3.0"/>
			<item value="nóż z kości" quantity="[1,1]" probability="50.0"/>
			<item value="kieł wilczy" quantity="[1,1]" probability="25.0"/>
			<item value="pazury wilcze" quantity="[1,1]" probability="25.0"/>
			<item value="spodnie barbarzyńcy" quantity="[1,1]" probability="5.0"/>
			<item value="rękawice barbarzyńcy" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Król powiedzieć - śmierć!"/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="barbarzyńca lider">
		<type class="human" subclass="barbarian_leader" tileid="human_barbarian.png:2"/>
		<description></description>
		<attributes>
			<atk value="492"/>
			<def value="75"/>
			<armor_type value="medium"/>
			<hp value="505"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="64"/>
		<experience value="4183"/>
		<respawn value="1960"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[10,50]" probability="100.0"/>
			<item value="zbroja barbarzyńcy" quantity="[1,1]" probability="5.0"/>
			<item value="pas barbarzyńcy" quantity="[1,1]" probability="1.0"/>
			<item value="rękawice barbarzyńcy" quantity="[1,1]" probability="1.0"/>
			<item value="młot chaosu" quantity="[1,1]" probability="0.5"/>
			<item value="młot wulkanów" quantity="[1,1]" probability="0.0050"/>
			<item value="bukłak z wodą" quantity="[1,2]" probability="1.5"/>
			<item value="półtorak" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Ja zniszczyć ciebie!"/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
			<profile name="attack weakest"/>
		</ai>
	</creature>

	<creature name="król barbarzyńca">
		<type class="human" subclass="barbarian_king" tileid="human_barbarian.png:6"/>
		<description></description>
		<attributes>
			<atk value="531"/>
			<def value="79"/>
			<armor_type value="medium"/>
			<hp value="600"/>
			<speed value="1.0"/>
			<size value="1,1"/>
		</attributes>
		<level value="75"/>
		<experience value="5265"/>
		<respawn value="2510"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[60,300]" probability="100.0"/>
			<item value="kamienna zbroja" quantity="[1,1]" probability="0.15"/>
			<item value="czarne buty" quantity="[1,1]" probability="0.025"/>
			<item value="kropacz" quantity="[1,1]" probability="1.0"/>
			<item value="maczeta" quantity="[1,1]" probability="50.0"/>
			<item value="młot chaosu" quantity="[1,1]" probability="0.5"/>
			<item value="bukłak z wodą" quantity="[1,3]" probability="1.5"/>
			<item value="tarcza chaosu" quantity="[1,1]" probability="0.005"/>
			<item value="buty barbarzyńcy" quantity="[1,1]" probability="25.0"/>
			<item value="płaszcz barbarzyńcy" quantity="[1,1]" probability="5.0"/>
			<item value="rękawice barbarzyńcy" quantity="[1,1]" probability="1.5"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="attack weakest"/>
		</ai>
	</creature>
</creatures>
