=== PolanieOnLine/PolanieOnLine/data/conf/creatures.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="stendhal" xmlns:tns="http://www.example.org/creatures"
	elementFormDefault="qualified" xmlns:Q2="stendhal">

	<xsd:element name="creatures" type="Q2:CreaturesType"></xsd:element>

	<xsd:complexType name="CreaturesType">
		<xsd:sequence>
			<xsd:element name="creature" type="Q2:CreatureType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="CreatureType">
		<xsd:sequence>
			<xsd:element name="type" type="Q2:Type" minOccurs="1" />
			<xsd:element name="hidden" type="xsd:string" minOccurs="0" />
			<xsd:element name="description" type="xsd:string" minOccurs="0" />
			<xsd:element name="attributes" type="Q2:Attributes" minOccurs="1" />
			<xsd:element name="level" type="Q2:Level" minOccurs="1" />
			<xsd:element name="experience" type="Q2:Experience"	minOccurs="1" />
			<xsd:element name="respawn" type="Q2:Respawn" />
			<xsd:element name="blood" type="Q2:Blood" minOccurs="0" />
			<xsd:element name="corpse" type="Q2:Corpse" />
			<xsd:element name="drops" type="Q2:Drops" minOccurs="0" />
			<xsd:element name="slots" type="Q2:Slots" minOccurs="0" />
			<xsd:element name="equips" type="Q2:Equips" minOccurs="0" />
			<xsd:element name="abilities" type="Q2:Abilities" minOccurs="0"/>
			<xsd:element name="ai" type="Q2:Ai" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="condition" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="quantity" type="xsd:string" />
		<xsd:attribute name="probability" type="xsd:double" />
	</xsd:complexType>

	<xsd:complexType name="SpecialItem">
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Q2:Item" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="special" type="Q2:SpecialItem" minOccurs="0"
        		maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Respawn">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="value" type="xsd:positiveInteger"/>
	</xsd:complexType>

	<xsd:complexType name="Blood">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Corpse">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="width" type="xsd:positiveInteger"/>
		<xsd:attribute name="height" type="xsd:positiveInteger"/>
		<xsd:attribute name="harmless" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ratk" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="armor_type" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" use="required">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:enumeration value="none" />
								<xsd:enumeration value="light" />
								<xsd:enumeration value="medium" />
								<xsd:enumeration value="heavy" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="armor_hp" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:nonNegativeInteger" use="required" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="resistance" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="visibility" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="state" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Q2:Says" minOccurs="0" />
			<xsd:element name="profile" type="Q2:Profile" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Q2:Text" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="text" type="Q2:Text" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="sound" type="Q2:Sound" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="movement" type="Q2:Movement" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="death" type="Q2:Death" minOccurs="0"
				maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Text">
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="state" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Sound">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Movement">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="Death">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="params" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string" />
		<xsd:attribute name="subclass" type="xsd:string" />
		<xsd:attribute name="shadow" type="xsd:string" />
		<xsd:attribute name="tileid" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer" />
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer" />
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="slot" type="Q2:Slot" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Abilities">
		<xsd:sequence>
			<xsd:element name="damage" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" default="cut"/>
					<xsd:attribute name="rangedType" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="susceptibility" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="statusattack" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Slot">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="item" type="xsd:string" use="required" />
		<xsd:attribute name="quantity" type="xsd:positiveInteger" />
	</xsd:complexType>
	
</xsd:schema>

=== PolanieOnLine/PolanieOnLine/data/conf/creatures/stendhal/kobold.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: kobold -->
	<creature name="kobold">
		<type class="kobold" subclass="kobold" tileid="kobold.png:1"/>
		<description>Oto kobold. We wsi gadają, że to mityczny duch.</description>
		<attributes>
			<atk value="80"/>
			<def value="16"/>
			<armor value="light"/>
			<hp value="50"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="5"/>
		<experience value="50"/>
		<respawn value="1200"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[2,6]" probability="90.0"/>
			<item value="skórzane spodnie" quantity="[1,1]" probability="10.0"/>
			<item value="skórzana zbroja" quantity="[1,1]" probability="10.0"/>
			<item value="skórzany kirys" quantity="[1,1]" probability="2.0"/>
			<item value="pas skórzany" quantity="[1,1]" probability="3.0"/>
			<item value="toporek" quantity="[1,1]" probability="1.3"/>
			<item value="buty skórzane" quantity="[1,1]" probability="0.5"/>
			<item value="puklerz" quantity="[1,1]" probability="0.5"/>
			<item value="nożyk" quantity="[1,1]" probability="0.5"/>
			<item value="butelka wody" quantity="[1,3]" probability="15.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Wrrrr! Hau!"/>
				<sound value="kobold-snort-01"/>
				<sound value="kobold_bark-01"/>
				<sound value="kobold_bark-02"/>
				<sound value="kobold_bark-03"/>
				<sound value="kobold_bark-04"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="kobold żołnierz">
		<type class="kobold" subclass="soldier_kobold" tileid="kobold.png:3"/>
		<description>Oto kobold żołnierz. Broni zaciekle swego króla.</description>
		<attributes>
			<atk value="93"/>
			<def value="20"/>
			<armor value="medium"/>
			<hp value="65"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="7"/>
		<experience value="70"/>
		<respawn value="1200"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[3,11]" probability="90.0"/>
			<item value="skórzana zbroja łuskowa" quantity="[1,1]" probability="10.0"/>
			<item value="zbroja ćwiekowa" quantity="[1,1]" probability="6.0"/>
			<item value="spodnie nabijane ćwiekami" quantity="[1,1]" probability="8.0"/>
			<item value="topór jednoręczny" quantity="[1,1]" probability="1.4"/>
			<item value="buty skórzane" quantity="[1,1]" probability="0.5"/>
			<item value="skórzany hełm" quantity="[1,1]" probability="1.0"/>
			<item value="drewniana tarcza" quantity="[1,1]" probability="1.3"/>
			<item value="pas kolczy" quantity="[1,1]" probability="1.5"/>
			<item value="mieczyk" quantity="[1,1]" probability="0.2"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Hau! Hauu!"/>
				<sound value="kobold-snort-01"/>
				<sound value="kobold_bark-01"/>
				<sound value="kobold_bark-02"/>
				<sound value="kobold_bark-03"/>
				<sound value="kobold_bark-04"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="kobold łucznik">
		<type class="kobold" subclass="archer_kobold" tileid="kobold.png:0"/>
		<description>Oto kobold łucznik, który trzyma się z daleka od napastnika.</description>
		<attributes>
			<atk value="94"/>
			<ratk value="94"/>
			<def value="28"/>
			<armor value="light"/>
			<hp value="40"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="8"/>
		<experience value="80"/>
		<respawn value="1200"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[3,10]" probability="90.0"/>
			<item value="skórzana zbroja łuskowa" quantity="[1,1]" probability="10.0"/>
			<item value="strzała" quantity="[3,12]" probability="6.0"/>
			<item value="buty skórzane" quantity="[1,1]" probability="0.5"/>
			<item value="drewniany sztylecik" quantity="[1,1]" probability="0.5"/>
			<item value="drewniany łuk" quantity="[1,1]" probability="0.5"/>
			<item value="złoty pas kolczy" quantity="[1,1]" probability="0.5"/>
		</drops>
		<equips>
			<slot name="lhand" item="strzała" quantity="10000" />
			<slot name="rhand" item="drewniany łuk" quantity="1" />
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Hssss! Hau sss!"/>
				<sound value="kobold-snort-01"/>
				<sound value="kobold_bark-01"/>
				<sound value="kobold_bark-02"/>
				<sound value="kobold_bark-03"/>
				<sound value="kobold_bark-04"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="archer"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="kobold weteran">
		<type class="kobold" subclass="veteran_kobold" tileid="kobold.png:4"/>
		<description>Oto kobold weteran. Nieźle włada bronią.</description>
		<attributes>
			<atk value="113"/>
			<def value="31"/>
			<armor value="medium"/>
			<hp value="50"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="9"/>
		<experience value="90"/>
		<respawn value="1200"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[3,13]" probability="90.0"/>
			<item value="drewniana tarcza" quantity="[1,1]" probability="10.0"/>
			<item value="tarcza płytowa" quantity="[1,1]" probability="50.0"/>
			<item value="kiścień" quantity="[1,1]" probability="10.0"/>
			<item value="skórzana zbroja" quantity="[1,1]" probability="10.0"/>
			<item value="topór" quantity="[1,1]" probability="2.0"/>
			<item value="nożyk" quantity="[1,1]" probability="0.7"/>
			<item value="buty nabijane ćwiekami" quantity="[1,1]" probability="0.5"/>
			<item value="skórzany hełm" quantity="[1,1]" probability="1.5"/>
			<item value="krótki miecz" quantity="[1,1]" probability="1.0"/>
			<item value="złoty pas kolczy" quantity="[1,1]" probability="1.0"/>
			<item value="butelka wody" quantity="[1,2]" probability="40.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<sound value="kobold-snort-01"/>
				<sound value="kobold_bark-01"/>
				<sound value="kobold_bark-02"/>
				<sound value="kobold_bark-03"/>
				<sound value="kobold_bark-04"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="kobold lider">
		<type class="kobold" subclass="leader_kobold" tileid="kobold.png:2"/>
		<description>Oto kobold lider. Jeden z wielkich wojowników.</description>
		<attributes>
			<atk value="139"/>
			<def value="39"/>
			<armor value="medium"/>
			<hp value="65"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="13"/>
		<experience value="314"/>
		<respawn value="1220"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[3,20]" probability="90.0"/>
			<item value="kolczuga" quantity="[1,1]" probability="8.0"/>
			<item value="kolczuga wzmocniona" quantity="[1,1]" probability="1.0"/>
			<item value="zbroja łuskowa" quantity="[1,1]" probability="0.05"/>
			<item value="żelazna zbroja łuskowa" quantity="[1,1]" probability="0.0050"/>
			<item value="topór bojowy" quantity="[1,1]" probability="1.5"/>
			<item value="buty kolcze" quantity="[1,1]" probability="1.5"/>
			<item value="buteleczka wody" quantity="[1,2]" probability="1.5"/>
			<item value="hełm kolczy" quantity="[1,1]" probability="3.0"/>
			<item value="tarcza płytowa" quantity="[1,1]" probability="0.5"/>
			<item value="pas kolczy" quantity="[1,1]" probability="2.0"/>
			<item value="butelka wody" quantity="[1,3]" probability="33.5"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<sound value="kobold-snort-01"/>
				<sound value="kobold_bark-01"/>
				<sound value="kobold_bark-02"/>
				<sound value="kobold_bark-03"/>
				<sound value="kobold_bark-04"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="attack weakest"/>
		</ai>
	</creature>

	<creature name="kobold olbrzymi">
		<type class="kobold" subclass="giant_kobold" tileid="kobold.png:5"/>
		<description>Oto kobold olbrzymi. Choć jest zabawny to nie jest świadomy swej siły. Kiedy zaproponuje przytulenie to najjlepiej jest odrzucić jego szczodrą ofertę.</description>
		<attributes>
			<atk value="440"/>
			<def value="57"/>
			<hp value="400"/>
			<speed value="1.0"/>
			<size value="2,2"/>
		</attributes>
		<level value="55"/>
		<experience value="2210"/>
		<respawn value="1650"/>
		<corpse name="giant_humanoid"/>
		<drops>
			<item value="money" quantity="[10,60]" probability="100.0"/>
			<item value="duży eliksir" quantity="[1,4]" probability="50.0"/>
			<item value="złota zbroja" quantity="[1,1]" probability="1.0"/>
			<item value="kropacz" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Tulu?"/>
				<sound value="kobold-snort-01"/>
				<sound value="kobold_bark-01"/>
				<sound value="kobold_bark-02"/>
				<sound value="kobold_bark-03"/>
				<sound value="kobold_bark-04"/>
			</says>
			<profile name="status_attackers" params="StunnedStatus,5;"/>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="lifesteal" params="0.3"/>
			<profile name="heal" params="5,50"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	<!-- END: kobold -->
</creatures>

=== PolanieOnLine/PolanieOnLine/data/conf/creatures/stendhal/human_risecia.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<creature name="risecia zbir">
		<type class="human" subclass="risecia_thug" tileid="human_risecia.png:1"/>
		<description>Oto risecia zbir. Trzymaj się od niego z daleka!</description>
		<attributes>
			<atk value="152"/>
			<def value="38"/>
			<armor_type value="medium"/>
			<hp value="60"/>
			<speed value="0.7"/>
			<size value="1,1"/>
		</attributes>
		<level value="12"/>
		<experience value="283"/>
		<respawn value="1210"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[3,20]" probability="90.0"/>
			<item value="kolczuga" quantity="[1,1]" probability="8.0"/>
			<item value="spodnie kolcze" quantity="[1,1]" probability="12.0"/>
			<item value="kolczuga wzmocniona" quantity="[1,1]" probability="1.3"/>
			<item value="kanapka" quantity="[1,1]" probability="1.5"/>
			<item value="buty kolcze" quantity="[1,1]" probability="1.0"/>
			<item value="peleryna" quantity="[1,1]" probability="0.5"/>
			<item value="hełm nabijany ćwiekami" quantity="[1,1]" probability="1.0"/>
			<item value="krótki miecz" quantity="[1,1]" probability="2.5"/>
			<item value="maczeta" quantity="[1,1]" probability="2.5"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="risecia łucznik">
		<type class="human" subclass="risecia_archer" tileid="human_risecia.png:0"/>
		<description>Oto risecia łucznik. Jeden z wielu, którzy bronią swego dowódcę.</description>
		<attributes>
			<atk value="159"/>
			<ratk value="159"/>
			<def value="38"/>
			<armor_type value="medium"/>
			<hp value="70"/>
			<speed value="0.6"/>
			<size value="1,1"/>
		</attributes>
		<level value="14"/>
		<experience value="340"/>
		<respawn value="1220"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[2,15]" probability="100.0"/>
			<item value="zbroja łuskowa" quantity="[1,1]" probability="2.0"/>
			<item value="żelazna zbroja łuskowa" quantity="[1,1]" probability="0.5"/>
			<item value="strzała" quantity="[4,12]" probability="10.0"/>
			<item value="buty kolcze" quantity="[1,1]" probability="5.0"/>
			<item value="drewniany łuk" quantity="[1,1]" probability="5.0"/>
		</drops>
		<equips>
			<slot name="rhand" item="drewniany łuk" quantity="1"/>
			<slot name="lhand" item="strzała" quantity="10000"/>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="archer"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="risecia z klingą">
		<type class="human" subclass="risecia_swordsman" tileid="human_risecia.png:2"/>
		<description>Oto risecia z klingą. Jego ostrze miecza zetnie Twoją głowę!</description>
		<attributes>
			<atk value="194"/>
			<def value="27"/>
			<armor_type value="medium"/>
			<hp value="150"/>
			<speed value="0.8"/>
			<size value="1,1"/>
		</attributes>
		<level value="17"/>
		<experience value="425"/>
		<respawn value="1240"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[3,25]" probability="100.0"/>
			<item value="zbroja łuskowa" quantity="[1,1]" probability="5.0"/>
			<item value="żelazna zbroja łuskowa" quantity="[1,1]" probability="1.0"/>
			<item value="żelazny kirys z naramiennikami" quantity="[1,1]" probability="0.05"/>
			<item value="buty żelazne" quantity="[1,1]" probability="0.5"/>
			<item value="hełm kolczy" quantity="[1,1]" probability="5.0"/>
			<item value="miecz" quantity="[1,1]" probability="1.5"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="Falatheen szef Risecia">
		<type class="human" subclass="risecia_leader" tileid="human_risecia.png:3"/>
		<description>Oto Falatheen szef Risecia. Nie chce zginąć! Jego mali wojownicy chronią go przed napastnikami.</description>
		<attributes>
			<atk value="209"/>
			<def value="22"/>
			<armor_type value="medium"/>
			<hp value="150"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="20"/>
		<experience value="503"/>
		<respawn value="1260"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[10,40]" probability="70.0"/>
			<item value="tarta" quantity="[1,1]" probability="5.0"/>
			<item value="żelazna zbroja łuskowa" quantity="[1,1]" probability="7.0"/>
			<item value="złota kolczuga" quantity="[1,1]" probability="2.0"/>
			<item value="żelazny kirys z naramiennikami" quantity="[1,1]" probability="0.5"/>
			<item value="buty kolcze" quantity="[1,1]" probability="6.0"/>
			<item value="peleryna" quantity="[1,1]" probability="5.0"/>
			<item value="misiurka" quantity="[1,1]" probability="1.0"/>
			<item value="bułat" quantity="[1,1]" probability="1.5"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="lifesteal" params="0.5"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
			<profile name="attack weakest"/>
		</ai>
	</creature>
</creatures>

=== PolanieOnLine/PolanieOnLine/data/conf/creatures/stendhal/undead.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: animal -->
	<creature name="duch psa">
		<type class="undead" subclass="ghosthound" tileid="undead.png:13"/>
		<description>Dostrzegając kudłaty kształt i błyszczące złe spojrzenie to przypominasz sobie wszystkie opowieści grozy o duchu psa!</description>
		<attributes>
			<atk value="320"/>
			<def value="110"/>
			<hp value="110"/>
			<speed value="0.8"/>
			<size value="1,1"/>
			<resistance value="50"/>
			<visibility value="60"/>
		</attributes>
		<level value="45"/>
		<experience value="1250"/>
		<!-- once in 6 weeks, but two are in the world -->
		<respawn value="12096000"/>
		<corpse name="animal"/>
		<drops>
			<item value="rubin" quantity="[1,1]" probability="3.0"/>
		</drops>
		<equips>
			<slot name="rhand" item="sztylet mroku" quantity="1"/>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="HaUuuu!"/>
				<noise state="fight" value="Grrrr!"/>
				<sound value="dog-snarl-1"/>
				<sound value="dog-snarl-2"/>
				<sound value="dog-angry-low-1"/>
			</says>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="patrolling"/>
			<profile name="lifesteal" params="0.05"/>
			<profile name="rare"/>
		</ai>
	</creature>
	<!-- END: animal -->

	<!-- START: misc -->
	<creature name="rycerz śmierci">
		<type class="undead" subclass="death_knight" tileid="undead.png:1"/>
		<description>Oto rycerz śmierci. Niegdyś walczył w wielu turniejach, w których jedynym zadaniem było zabić każdego przeciwnika.</description>
		<attributes>
			<atk value="421"/>
			<def value="52"/>
			<armor_type value="heavy"/>
			<hp value="500"/>
			<armor_hp value="125"/>
			<speed value="1.0"/>
			<size value="1,1"/>
			<resistance value="100"/>
			<visibility value="100"/>
		</attributes>
		<level value="52"/>
		<experience value="1920"/>
		<respawn value="1620"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[4,60]" probability="100.0"/>
			<item value="złota zbroja" quantity="[1,1]" probability="0.5"/>
			<item value="zbroja cieni" quantity="[1,1]" probability="0.0050"/>
			<item value="buty cieni" quantity="[1,1]" probability="1.5"/>
			<item value="hełm cieni" quantity="[1,1]" probability="0.35"/>
			<item value="miecz ognisty" quantity="[1,1]" probability="0.5"/>
			<item value="czarny sztylet" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="heal" params="5,50"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="necrosophia">
		<type class="hybrid" subclass="necrosophia" tileid="hybrid.png:7"/>
		<description>Oto Necrosophia. Jest mocną bestią. Spali cię na popiół, gdy jesteś zdezorientowany przez magiczne fasolki.</description>
		<attributes>
			<atk value="1292"/>
			<def value="154"/>
			<armor_type value="none"/>
			<hp value="4118"/>
			<speed value="0.8"/>
			<size value="4,3"/>
		</attributes>
		<level value="250"/>
		<experience value="150000"/>
		<respawn value="3000"/>
		<corpse name="huger_animal" width="4" height="4"/>
		<drops>
			<item value="wielki eliksir" quantity="[1,2]" probability="50.0"/>
			<item value="płaszcz mainiocyjski" quantity="[1,1]" probability="2.5"/>
			<item value="hełm mainiocyjski" quantity="[1,1]" probability="2.0"/>
			<item value="spodnie mainiocyjskie" quantity="[1,1]" probability="2.5"/>
			<item value="buty mainiocyjskie" quantity="[1,1]" probability="2.5"/>
			<item value="tarcza mainiocyjska" quantity="[1,1]" probability="2.5"/>
			<item value="zbroja mainiocyjska" quantity="[1,1]" probability="1.0"/>
			<item value="rękawice mainiocyjskie" quantity="[1,1]" probability="1.0"/>
			<item value="pas mainiocyjski" quantity="[1,1]" probability="1.5"/>
			<item value="miecz mainiocyjski" quantity="[1,1]" probability="1.0"/>
		</drops>
		<equips>
		</equips>
		<abilities>
			<damage type="fire"/>
		</abilities>
		<ai>
			<profile name="status_attackers" params="StunnedStatus,10;"/>
			<profile name="brave"/>
			<profile name="animal"/>
			<profile name="offensive"/>
			<profile name="heal" params="30,50"/>
			<profile name="patrolling"/>
			<profile name="boss"/>
		</ai>
	</creature>
	<!-- END: misc -->

	<!-- START: specter -->
	<creature name="zielona zjawa">
		<type class="undead" subclass="green_phantom" tileid="undead.png:12"/>
		<attributes>
			<atk value="462"/>
			<def value="65"/>
			<armor_type value="none"/>
			<hp value="500"/>
			<speed value="0.8"/>
			<size value="1,1"/>
			<resistance value="50"/>
			<visibility value="50"/>
		</attributes>
		<level value="60"/>
		<experience value="2710"/>
		<respawn value="1700"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="spodnie cieni" quantity="[1,1]" probability="0.3"/>
			<item value="bułat" quantity="[1,1]" probability="2.0"/>
			<item value="klinga orków" quantity="[1,1]" probability="2.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>
	<!-- END: specter -->
</creatures>
