=== PolanieOnLine/PolanieOnLine/data/conf/creatures.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="stendhal" xmlns:tns="http://www.example.org/creatures"
	elementFormDefault="qualified" xmlns:Q2="stendhal">

	<xsd:element name="creatures" type="Q2:CreaturesType"></xsd:element>

	<xsd:complexType name="CreaturesType">
		<xsd:sequence>
			<xsd:element name="creature" type="Q2:CreatureType"
				minOccurs="0" maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="CreatureType">
		<xsd:sequence>
			<xsd:element name="type" type="Q2:Type" minOccurs="1" />
			<xsd:element name="hidden" type="xsd:string" minOccurs="0" />
			<xsd:element name="description" type="xsd:string" minOccurs="0" />
			<xsd:element name="attributes" type="Q2:Attributes" minOccurs="1" />
			<xsd:element name="level" type="Q2:Level" minOccurs="1" />
			<xsd:element name="experience" type="Q2:Experience"	minOccurs="1" />
			<xsd:element name="respawn" type="Q2:Respawn" />
			<xsd:element name="blood" type="Q2:Blood" minOccurs="0" />
			<xsd:element name="corpse" type="Q2:Corpse" />
			<xsd:element name="drops" type="Q2:Drops" minOccurs="0" />
			<xsd:element name="slots" type="Q2:Slots" minOccurs="0" />
			<xsd:element name="equips" type="Q2:Equips" minOccurs="0" />
			<xsd:element name="abilities" type="Q2:Abilities" minOccurs="0"/>
			<xsd:element name="ai" type="Q2:Ai" minOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="condition" type="xsd:string" use="optional" />
	</xsd:complexType>

	<xsd:complexType name="Item">
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="quantity" type="xsd:string" />
		<xsd:attribute name="probability" type="xsd:double" />
	</xsd:complexType>

	<xsd:complexType name="SpecialItem">
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Drops">
		<xsd:sequence>
			<xsd:element name="item" type="Q2:Item" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="special" type="Q2:SpecialItem" minOccurs="0"
        		maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Respawn">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="value" type="xsd:positiveInteger"/>
	</xsd:complexType>

	<xsd:complexType name="Blood">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
	</xsd:complexType>

	<xsd:complexType name="Corpse">
		<xsd:attribute name="name" type="xsd:string" use="required"/>
		<xsd:attribute name="width" type="xsd:positiveInteger"/>
		<xsd:attribute name="height" type="xsd:positiveInteger"/>
		<xsd:attribute name="harmless" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Attributes">
		<xsd:sequence>
			<xsd:element name="atk" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="ratk" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="def" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="armor_type" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" use="required">
						<xsd:simpleType>
							<xsd:restriction base="xsd:string">
								<xsd:enumeration value="none" />
								<xsd:enumeration value="light" />
								<xsd:enumeration value="medium" />
								<xsd:enumeration value="heavy" />
							</xsd:restriction>
						</xsd:simpleType>
					</xsd:attribute>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="hp" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="armor_hp" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:nonNegativeInteger" use="required" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="speed" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="size" minOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="resistance" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="visibility" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="value" type="xsd:positiveInteger" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="noise" minOccurs="0">
				<xsd:complexType>
					<xsd:attribute name="state" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:string" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Ai">
		<xsd:sequence>
			<xsd:element name="says" type="Q2:Says" minOccurs="0" />
			<xsd:element name="profile" type="Q2:Profile" minOccurs="1"
				maxOccurs="unbounded" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Says">
		<xsd:sequence>
			<xsd:element name="noise" type="Q2:Text" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="text" type="Q2:Text" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="sound" type="Q2:Sound" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="movement" type="Q2:Movement" minOccurs="0"
				maxOccurs="unbounded" />
			<xsd:element name="death" type="Q2:Death" minOccurs="0"
				maxOccurs="1" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Text">
		<xsd:attribute name="value" type="xsd:string" />
		<xsd:attribute name="state" type="xsd:string"></xsd:attribute>
	</xsd:complexType>

	<xsd:complexType name="Sound">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Movement">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>
	
	<xsd:complexType name="Death">
		<xsd:attribute name="value" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Profile">
		<xsd:attribute name="name" type="xsd:string" />
		<xsd:attribute name="params" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Type">
		<xsd:attribute name="class" type="xsd:string" />
		<xsd:attribute name="subclass" type="xsd:string" />
		<xsd:attribute name="shadow" type="xsd:string" />
		<xsd:attribute name="tileid" type="xsd:string" />
	</xsd:complexType>

	<xsd:complexType name="Level">
		<xsd:attribute name="value" type="xsd:integer" />
	</xsd:complexType>

	<xsd:complexType name="Experience">
		<xsd:attribute name="value" type="xsd:integer" />
	</xsd:complexType>

	<xsd:complexType name="Slots">
		<xsd:sequence>
			<xsd:element name="slot" type="xsd:string" minOccurs="0" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Equips">
		<xsd:sequence>
			<xsd:element name="slot" type="Q2:Slot" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Abilities">
		<xsd:sequence>
			<xsd:element name="damage" minOccurs="0" maxOccurs="1">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" default="cut"/>
					<xsd:attribute name="rangedType" type="xsd:string"/>
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="susceptibility" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
			<xsd:element name="statusattack" minOccurs="0" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:attribute name="type" type="xsd:string" />
					<xsd:attribute name="value" type="xsd:decimal" />
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="Slot">
		<xsd:sequence>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required" />
		<xsd:attribute name="item" type="xsd:string" use="required" />
		<xsd:attribute name="quantity" type="xsd:positiveInteger" />
	</xsd:complexType>
	
</xsd:schema>

=== PolanieOnLine/PolanieOnLine/data/conf/creatures/stendhal/gnome.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: gnome -->

	<creature name="gnom">
		<type class="gnome" subclass="gnome" tileid="gnome.png:0"/>
		<description>Oto gnom. Żyje w górach.</description>
		<attributes>
			<atk value="46"/>
			<def value="7"/>
			<armor value="light"/>
			<hp value="50"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="2"/>
		<experience value="20"/>
		<respawn value="900"/>
		<corpse name="tiny_humanoid" harmless="gnome" />
		<drops>
			<item value="money" quantity="[2,5]" probability="70.0"/>
			<item value="mały eliksir" quantity="[1,1]" probability="5.0"/>
			<item value="pieczarka" quantity="[3,6]" probability="10.0"/>
			<item value="skórzana zbroja" quantity="[1,1]" probability="10.0"/>
			<item value="puklerz" quantity="[1,1]" probability="5.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Gigaaaanty! Uciekaaaaj!"/>
			</says>
			<profile name="offensive"/>
			<profile name="coward"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="panna gnom">
		<type class="gnome" subclass="woman_gnome" tileid="gnome.png:1"/>
		<description>Oto panna gnom. Wciąż poleruje skały w górach.</description>
		<attributes>
			<atk value="47"/>
			<def value="7"/>
			<armor value="light"/>
			<hp value="50"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="2"/>
		<experience value="20"/>
		<respawn value="900"/>
		<corpse name="tiny_humanoid" harmless="gnome" />
		<drops>
			<item value="money" quantity="[2,5]" probability="70.0"/>
			<item value="buteleczka wody" quantity="[1,3]" probability="30.0"/>
			<item value="antidotum" quantity="[1,1]" probability="10.0"/>
			<item value="borowik" quantity="[1,10]" probability="10.0"/>
			<item value="skórzana zbroja" quantity="[1,1]" probability="10.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Gigaaaanty! Uciekaaaajmy!"/>
			</says>
			<profile name="offensive"/>
			<profile name="coward"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: gnome -->

	<!-- START: militant -->

	<creature name="gnom zwiadowca">
		<type class="gnome" subclass="infantryman" tileid="gnome.png:2"/>
		<description>Oto gnom zwiadowca. Będzie bronił wioski póki... nie ucieknie.</description>
		<attributes>
			<atk value="58"/>
			<def value="15"/>
			<armor value="light"/>
			<hp value="60"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="5"/>
		<experience value="50"/>
		<respawn value="1200"/>
		<corpse name="tiny_humanoid" harmless="gnome_military" />
		<drops>
			<item value="money" quantity="[4,10]" probability="70.0"/>
			<item value="marchew" quantity="[2,10]" probability="20.0"/>
			<item value="borowik" quantity="[1,10]" probability="10.0"/>
			<item value="buteleczka wody" quantity="[1,4]" probability="25.0"/>
			<item value="butelka wody" quantity="[1,2]" probability="15.0"/>
			<item value="proca" quantity="[1,1]" probability="10.0"/>
		</drops>
		<equips>
			<slot name="rhand" item="sztylecik"/>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Gotowy, aby uciekać?"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="gnom kawalerzysta">
		<type class="gnome" subclass="cavalryman" tileid="gnome.png:3"/>
		<description>Oto gnom kawalerzysta. Zapuszcza się daleko szukając złota.</description>
		<attributes>
			<atk value="90"/>
			<def value="14"/>
			<armor value="medium"/>
			<hp value="65"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="5"/>
		<experience value="50"/>
		<respawn value="1200"/>
		<corpse name="tiny_humanoid" harmless="gnome_military" />
		<drops>
			<item value="money" quantity="[6,14]" probability="70.0"/>
			<item value="buty kolcze" quantity="[1,1]" probability="15.0"/>
			<item value="kapelusz leśniczego" quantity="[1,1]" probability="20.0"/>
			<item value="buteleczka wody" quantity="[1,3]" probability="25.0"/>
			<item value="butelka wody" quantity="[1,2]" probability="15.0"/>
			<item value="skóra zwierzęca" quantity="[1,1]" probability="6.0"/>
			<item value="proca" quantity="[1,1]" probability="40.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Przygotowany do ucieczki?"/>
				<sound value="pig-squeal-01"/>
			</says>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: militant -->

	<!-- START: giant -->

	<creature name="olbrzymi gnom">
		<type class="gnome" subclass="gnome_giant" tileid="gnome.png:4"/>
		<description></description>
		<attributes>
			<atk value="322"/>
			<def value="79"/>
			<armor value="medium"/>
			<hp value="720"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="74"/>
		<experience value="4750"/>
		<respawn value="2420"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[6,50]" probability="70.0"/>
			<item value="eliksir" quantity="[1,1]" probability="20.0"/> 
			<item value="borowik" quantity="[1,10]" probability="10.0"/>
		</drops>
		<ai>
			<profile name="status_attackers" params="StunnedStatus,6;"/>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="olbrzymia panna gnom">
		<type class="gnome" subclass="gnomess_giant" tileid="gnome.png:5"/>
		<description></description>
		<attributes>
			<atk value="332"/>
			<def value="83"/>
			<armor value="medium"/>
			<hp value="760"/>
			<speed value="0.9"/>
			<size value="1,1"/>
		</attributes>
		<level value="76"/>
		<experience value="5200"/>
		<respawn value="2520"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[6,50]" probability="70.0"/>
			<item value="eliksir" quantity="[1,1]" probability="20.0"/> 
			<item value="borowik" quantity="[1,10]" probability="10.0"/>
		</drops>
		<ai>
			<profile name="status_attackers" params="StunnedStatus,6;"/>
			<profile name="brave"/>
			<profile name="offensive"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: giant -->
</creatures>

=== PolanieOnLine/PolanieOnLine/data/conf/creatures/pol/angel.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: serafiny -->
	<creature name="serafin">
		<type class="angel" subclass="serafin" tileid="pol_serafiny.png:0"/>
		<description>Oto serafin. Anioł najwyższego rzędu, strzęgącego tronu Niebios.</description>
		<attributes>
			<atk value="8888"/>
			<ratk value="8888"/>
			<def value="362"/>
			<armor value="heavy"/>
			<hp value="9000"/>
			<speed value="1.0"/>
			<size value="3,3"/>
		</attributes>
		<level value="880"/>
		<experience value="763000"/>
		<respawn value="190000"/>
		<corpse name="giant_humanoid"/>
		<drops>
			<item value="money" quantity="[100,20000]" probability="100.0"/>
			<item value="gigantyczny eliksir" quantity="[1,9]" probability="40.0"/>
			<item value="miecz nieśmiertelnych" quantity="[1,1]" probability="3.0"/>
			<item value="rękawice z mithrilu" quantity="[1,1]" probability="0.3"/>
			<item value="pas z mithrilu" quantity="[1,1]" probability="0.5"/>
			<item value="pióro serafina" quantity="[1,1]" probability="85.0"/>
			<item value="magia światła" quantity="[11,99]" probability="100.0"/>
			<item value="różdżka Wołosa" quantity="[1,1]" probability="20.0"/>
			<item value="pierścień z mithrilu" quantity="[1,1]" probability="0.1"/>
			<item value="kosa z mithrilu" quantity="[1,1]" probability="0.3"/>
		</drops>
		<equips>
			<slot name="lhand" item="magia światła" quantity="10000"/>
			<slot name="rhand" item="różdżka Peruna" quantity="1"/>
		</equips>
		<abilities>
			<damage type="light"/>
			<susceptibility type="dark" value="1.2"/>
			<susceptibility type="light" value="0.7"/>
		</abilities>
		<ai>
			<says>
				<noise state="idle follow fight" value="Niech twa dusza powróci na ziemię!"/>
			</says>
			<profile name="bleeding_attack" params="5"/>
			<profile name="brave"/>
			<profile name="archer"/>
			<profile name="offensive"/>
			<profile name="heal" params="10,50"/>
			<profile name="lifesteal" params="0.1"/>
			<profile name="attack weakest"/>
			<profile name="boss"/>
		</ai>
	</creature>

	<creature name="azazel">
		<type class="angel" subclass="azazel" tileid="pol_serafiny.png:1"/>
		<description>Oto azazel. Pomimo upadku wciąż jest uznawany za jednego z potężnych aniołów!</description>
		<attributes>
			<atk value="12222"/>
			<ratk value="12222"/>
			<def value="666"/>
			<armor value="heavy"/>
			<hp value="9000"/>
			<speed value="1.0"/>
			<size value="3,3"/>
		</attributes>
		<level value="990"/>
		<experience value="963000"/>
		<respawn value="190000"/>
		<corpse name="giant_humanoid"/>
		<drops>
			<item value="money" quantity="[100,30000]" probability="100.0"/>
			<item value="gigantyczny eliksir" quantity="[1,9]" probability="40.0"/>
			<item value="czarny miecz" quantity="[1,1]" probability="5.0"/>
			<item value="czarne rękawice" quantity="[1,1]" probability="5.0"/>
			<item value="czarny pas" quantity="[1,1]" probability="1.0"/>
			<item value="pióro azazela" quantity="[1,1]" probability="85.0"/>
			<item value="magia mroku" quantity="[11,99]" probability="90.0"/>
			<item value="różdżka Peruna" quantity="[1,1]" probability="0.3"/>
			<item value="czarny pierścień" quantity="[1,1]" probability="0.2"/>
			<item value="pierścień niewidzialności" quantity="[1,1]" probability="0.1"/>
		</drops>
		<equips>
			<slot name="lhand" item="magia mroku" quantity="10000"/>
			<slot name="rhand" item="różdżka Peruna" quantity="1"/>
		</equips>
		<abilities>
			<damage type="dark"/>
			<susceptibility type="dark" value="0.7"/>
			<susceptibility type="light" value="1.2"/>
		</abilities>
		<ai>
			<says>
				<noise state="idle follow fight" value="Syn ognia nie będzie się kłaniał synowi ziemi!"/>
			</says>
			<profile name="bleeding_attack" params="5"/>
			<profile name="brave"/>
			<profile name="archer"/>
			<profile name="offensive"/>
			<profile name="heal" params="15,50"/>
			<profile name="lifesteal" params="0.2"/>
			<profile name="attack weakest"/>
			<profile name="boss"/>
		</ai>
	</creature>

	<creature name="cherubin">
		<type class="angel" subclass="cherubin" tileid="pol_serafiny.png:2"/>
		<description>Oto cherubin. Stojąca wysoko w hierarchii i potężna istota nadprzyrodzona, strzegąca ludzi przed demonami.</description>
		<attributes>
			<atk value="24444"/>
			<ratk value="24444"/>
			<def value="776"/>
			<armor value="heavy"/>
			<hp value="20000"/>
			<speed value="1.0"/>
			<size value="3,3"/>
		</attributes>
		<level value="1100"/>
		<experience value="1718000"/>
		<respawn value="380000"/>
		<corpse name="giant_humanoid"/>
		<drops>
			<item value="money" quantity="[100,40000]" probability="100.0"/>
			<item value="gigantyczny eliksir" quantity="[2,14]" probability="40.0"/>
			<item value="pióro cherubina" quantity="[1,1]" probability="90.0"/>
			<item value="magia mrozu" quantity="[11,222]" probability="100.0"/>
			<item value="różdżka Wołosa" quantity="[1,1]" probability="5.0"/>
			<item value="magiczny topór obosieczny" quantity="[1,1]" probability="3.0"/>
			<item value="zbroja z mithrilu" quantity="[1,1]" probability="0.5"/>
			<item value="hełm z mithrilu" quantity="[1,1]" probability="0.7"/>
			<item value="pierścień z mithrilu" quantity="[1,1]" probability="0.25"/>
			<item value="rękawice z mithrilu" quantity="[1,1]" probability="0.7"/>
			<item value="kosa z mithrilu" quantity="[1,1]" probability="0.5"/>
			<item value="miecz z mithrilu" quantity="[1,1]" probability="0.5"/>
			<item value="sztylecik z mithrilu" quantity="[1,1]" probability="0.3"/>
		</drops>
		<equips>
			<slot name="lhand" item="magia światła" quantity="10000"/>
			<slot name="rhand" item="różdżka Peruna" quantity="1"/>
		</equips>
		<abilities>
			<damage type="ice"/>
			<susceptibility type="ice" value="0.6"/>
			<susceptibility type="water" value="1.2"/>
			<susceptibility type="fire" value="1.2"/>
		</abilities>
		<ai>
			<says>
				<noise state="idle follow fight" value="Grzechy twej duszy ranią naszego Stwórcę!"/>
			</says>
			<profile name="bleeding_attack" params="5"/>
			<profile name="brave"/>
			<profile name="archer"/>
			<profile name="offensive"/>
			<profile name="heal" params="20,100"/>
			<profile name="lifesteal" params="0.3"/>
			<profile name="attack weakest"/>
			<profile name="boss"/>
		</ai>
	</creature>

	<creature name="lilith">
		<type class="angel" subclass="lilith" tileid="pol_serafiny.png:3"/>
		<description>Oto lilith. Jedna z najpotężniejszych upiorzyc, demonów oraz niezwykle groźna.</description>
		<attributes>
			<atk value="28888"/>
			<ratk value="28888"/>
			<def value="827"/>
			<hp value="24000"/>
			<speed value="1.0"/>
			<size value="3,3"/>
		</attributes>
		<level value="1210"/>
		<experience value="1918000"/>
		<respawn value="380000"/>
		<corpse name="giant_humanoid"/>
		<drops>
			<item value="money" quantity="[666,66666]" probability="100.0"/>
			<item value="gigantyczny eliksir" quantity="[3,21]" probability="40.0"/>
			<item value="pióro lilith" quantity="[1,1]" probability="90.0"/>
			<item value="magia mroku" quantity="[11,99]" probability="100.0"/>
			<item value="tarcza cieni" quantity="[1,1]" probability="1.5"/>
			<item value="czarna halabarda" quantity="[1,1]" probability="1.0"/>
			<item value="różdżka Peruna" quantity="[1,1]" probability="0.8"/>
			<item value="czarny hełm" quantity="[1,1]" probability="2.5"/>
			<item value="piekielny sztylet" quantity="[1,1]" probability="4.0"/>
			<item value="młot wulkanów" quantity="[1,1]" probability="0.5"/>
			<item value="czarna kosa" quantity="[1,1]" probability="1.0"/>
			<item value="czarny pierścień" quantity="[1,1]" probability="1.0"/>
			<item value="pierścień niewidzialności" quantity="[1,1]" probability="0.3"/>
		</drops>
		<equips>
			<slot name="lhand" item="magia mroku" quantity="10000"/>
			<slot name="rhand" item="różdżka Peruna" quantity="1"/>
		</equips>
		<abilities>
			<damage type="fire"/>
			<susceptibility type="water" value="1.2"/>
			<susceptibility type="ice" value="1.2"/>
			<susceptibility type="fire" value="0.6"/>
		</abilities>
		<ai>
			<says>
				<noise state="idle follow fight" value="Jestem wszystkim, czego nie możesz kontrolować."/>
				<noise state="idle follow fight" value="Precz stąd nim spojrzę!"/>
			</says>
			<profile name="bleeding_attack" params="5"/>
			<profile name="brave"/>
			<profile name="archer"/>
			<profile name="offensive"/>
			<profile name="heal" params="10,70"/>
			<profile name="lifesteal" params="0.4"/>
			<profile name="attack weakest"/>
			<profile name="boss"/>
		</ai>
	</creature>
	<!-- END: serafiny -->
</creatures>

=== PolanieOnLine/PolanieOnLine/data/conf/creatures/stendhal/goblin.xml
<?xml version="1.0" encoding="UTF-8"?>
<creatures xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../../creatures.xsd ">

	<!-- START: goblin -->

	<creature name="goblin">
		<type class="goblin" subclass="goblin" tileid="goblin.png:0"/>
		<description>Oto goblin. Jest naprawdę złym i psotliwym stworzeniem.</description>
		<attributes>
			<atk value="88"/>
			<def value="11"/>
			<armor_type value="light"/>
			<hp value="85"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="5"/>
		<experience value="50"/>
		<respawn value="1200"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[2,6]" probability="90.0"/>
			<item value="tarta" quantity="[1,1]" probability="1.0"/>
			<item value="skórzana zbroja" quantity="[1,1]" probability="10.0"/>
			<item value="skórzany kirys" quantity="[1,1]" probability="2.5"/>
			<item value="buty skórzane" quantity="[1,1]" probability="0.5"/>
			<item value="kij" quantity="[1,1]" probability="1.0"/>
			<item value="puklerz" quantity="[1,1]" probability="0.5"/>
			<item value="mieczyk" quantity="[1,1]" probability="0.5"/>
			<item value="koszula" quantity="[1,1]" probability="5.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Mmmm! Idzie mięsko!" />
				<sound value="goblin-01"/>
				<sound value="goblin-burp-01"/>
				<sound value="goblin-laugh-01"/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="goblin weteran">
		<type class="goblin" subclass="veteran_goblin" tileid="goblin.png:2"/>
		<description>Oto goblin weteran. Podstarzały wojownik...</description>
		<attributes>
			<atk value="106"/>
			<def value="14"/>
			<armor_type value="light"/>
			<hp value="120"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="7"/>
		<experience value="70"/>
		<respawn value="1200"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[4,11]" probability="90.0"/>
			<item value="skórzany kirys z naramiennikami" quantity="[1,1]" probability="10.0"/>
			<item value="spodnie nabijane ćwiekami" quantity="[1,1]" probability="10.0"/>
			<item value="zbroja ćwiekowa" quantity="[1,1]" probability="4.0"/>
			<item value="buty skórzane" quantity="[1,1]" probability="0.5"/>
			<item value="peleryna" quantity="[1,1]" probability="0.5"/>
			<item value="buzdygan" quantity="[1,1]" probability="2.0"/>
			<item value="drewniana tarcza" quantity="[1,1]" probability="1.0"/>
			<item value="koszula" quantity="[1,1]" probability="5.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<noise state="idle follow fight" value="Czas na śniadanko!" />
				<sound value="goblin-01"/>
				<sound value="goblin-burp-01"/>
				<sound value="goblin-laugh-01"/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<creature name="goblin żołnierz">
		<type class="goblin" subclass="soldier_goblin" tileid="goblin.png:1"/>
		<description>Oto goblin żołnierz. Jest młody ale doświadczony w boju.</description>
		<attributes>
			<atk value="127"/>
			<def value="39"/>
			<armor_type value="medium"/>
			<hp value="40"/>
			<speed value="0.5"/>
			<size value="1,1"/>
		</attributes>
		<level value="9"/>
		<experience value="90"/>
		<respawn value="1200"/>
		<corpse name="humanoid"/>
		<drops>
			<item value="money" quantity="[4,13]" probability="90.0"/>
			<item value="tarcza płytowa" quantity="[1,1]" probability="5.0"/>
			<item value="miecz" quantity="[1,1]" probability="5.0"/>
			<item value="zbroja ćwiekowa" quantity="[1,1]" probability="10.0"/>
			<item value="kolczuga" quantity="[1,1]" probability="0.4"/>
			<item value="spodnie kolcze" quantity="[1,1]" probability="0.8"/>
			<item value="buty nabijane ćwiekami" quantity="[1,1]" probability="0.4"/>
			<item value="peleryna" quantity="[1,1]" probability="0.4"/>
			<item value="kiścień" quantity="[1,1]" probability="1.0"/>
			<item value="krótki miecz" quantity="[1,1]" probability="1.0"/>
			<item value="koszula" quantity="[1,1]" probability="5.0"/>
		</drops>
		<equips>
		</equips>
		<ai>
			<says>
				<sound value="goblin-01"/>
				<sound value="goblin-burp-01"/>
				<sound value="goblin-laugh-01"/>
			</says>
			<profile name="offensive"/>
			<profile name="human"/>
			<profile name="patrolling"/>
		</ai>
	</creature>

	<!-- END: goblin -->

</creatures>
