=== PolanieOnLine/PolanieOnLine/data/conf/items.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">

	<element name="items" type="Q1:itemGroup"></element>

	<complexType name="itemGroup">
		<sequence>
			<element name="item" type="Q1:itemType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<simpleType name="tooltipCategory">
		<restriction base="string">
			<enumeration value="weapon"/>
			<enumeration value="armour"/>
			<enumeration value="accessory"/>
			<enumeration value="other"/>
		</restriction>
	</simpleType>

	<complexType name="itemType">
		<sequence>
			<element name="type" type="Q1:typeType" />
			<element name="description" type="string"></element>
			<element name="implementation" type="Q1:implementation"></element>
			<element name="unattainable" type="anyType" minOccurs="0" maxOccurs="1"></element>
			<element name="behavior" type="Q1:behavior" minOccurs="0" maxOccurs="1"></element>
			<element name="attributes" type="Q1:attributes"></element>
			<element name="weight" type="Q1:attribute" minOccurs="0" maxOccurs="1" />
			<element name="value" type="Q1:attribute" minOccurs="0" maxOccurs="1" />
			<element name="preview" type="string" minOccurs="0" maxOccurs="1" />
			<element name="susceptibility" type="Q1:susceptibility" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="equipable" type="Q1:equipable"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="condition" type="string"></attribute>
		<attribute name="rarity-enabled" type="boolean"></attribute>
		<attribute name="rarity-profile" type="string"></attribute>
		<attribute name="tooltip-category" type="Q1:tooltipCategory"></attribute>
	</complexType>

	<complexType name="typeType">
		<attribute name="class" type="string"></attribute>
		<attribute name="subclass" type="string"></attribute>
		<attribute name="tileid" type="int"></attribute>
	</complexType>

	<complexType name="implementation">
		<attribute name="class-name" type="string"></attribute>
	</complexType>
	
	<complexType name="behavior">
		<sequence>
			<element name="parameter" type="Q1:pair" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="class-name" type="string"/>
	</complexType>
	
	<complexType name="pair">
		<attribute name="name" type="string"/>
		<attribute name="value" type="string"/>
	</complexType>

	<complexType name="attributes">
		<sequence>
			<element name="itemdata" type="Q1:attribute" minOccurs="0"/>
			<element name="atk" type="Q1:attribute" minOccurs="0"/>
			<element name="ratk" type="Q1:attribute" minOccurs="0"/>
			<element name="damage_min" type="Q1:attribute" minOccurs="0"/>
			<element name="damage_max" type="Q1:attribute" minOccurs="0"/>
			<element name="def" type="Q1:attribute" minOccurs="0"/>
			<element name="immunization" type="Q1:attribute" minOccurs="0"/>
			<element name="amount" type="Q1:attribute" minOccurs="0" maxOccurs="unbounded"/>
			<element name="frequency" type="Q1:attribute" minOccurs="0" maxOccurs="unbounded"/>
			<element name="range" type="Q1:attribute" minOccurs="0"/>
			<element name="quantity" type="Q1:attribute" minOccurs="0"/>
			<element name="max_quantity" type="Q1:attribute" minOccurs="0"/>
			<element name="regen" type="Q1:attribute" minOccurs="0" maxOccurs="unbounded"/>
			<element name="lifesteal" type="Q1:attribute" minOccurs="0"/>
			<element name="parry_chance" type="Q1:attribute" minOccurs="0"/>
			<element name="armor_penetration" type="Q1:attribute" minOccurs="0"/>
			<element name="critical_damage_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="bleed_on_hit" type="Q1:attribute" minOccurs="0"/>
			<element name="execute_damage" type="Q1:attribute" minOccurs="0"/>
			<element name="poison_on_hit" type="Q1:attribute" minOccurs="0"/>
			<element name="distance_damage" type="Q1:attribute" minOccurs="0"/>
			<element name="flat_attack_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="flat_defense_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_poisoned" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_bleeding" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_shocked" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_confused" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_heavy" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_stunned" type="Q1:attribute" minOccurs="0"/>
			<element name="skill_atk" type="Q1:attribute" minOccurs="0"/>
			<element name="atk_additional_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="critical_additional_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="def_additional_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="rate_increase" type="Q1:attribute" minOccurs="0"/>
			<element name="critical_chance" type="Q1:attribute" minOccurs="0"/>
			<element name="critical_bonus_reduction" type="Q1:attribute" minOccurs="0"/>
			<element name="out_of_combat_regen" type="Q1:attribute" minOccurs="0"/>
			<element name="consumable_healing_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="physical_dodge_chance" type="Q1:attribute" minOccurs="0"/>
			<element name="low_health_damage_reduction" type="Q1:attribute" minOccurs="0"/>
			<element name="nightmare_chance" type="Q1:attribute" minOccurs="0"/>
			<element name="lifesteal_increase" type="Q1:attribute" minOccurs="0"/>
			<element name="health" type="Q1:attribute" minOccurs="0"/>
			<element name="persistent" type="Q1:attribute" minOccurs="0"/>
			<element name="life_support" type="Q1:attribute" minOccurs="0"/>
			<element name="slot_name" type="Q1:attribute" minOccurs="0"/>
			<element name="undroppableondeath" type="Q1:attribute" minOccurs="0"/>
			<element name="autobind" type="Q1:attribute" minOccurs="0"/>
			<element name="slot_size" type="Q1:attribute" minOccurs="0"/>
			<element name="menu" type="Q1:attribute" minOccurs="0"/>
			<element name="durability" type="Q1:attribute" minOccurs="0" maxOccurs="1"/>
			<element name="itemset" type="Q1:attribute" minOccurs="0"/>
			<element name="use_sound" type="Q1:attribute" minOccurs="0" maxOccurs="1"/>
		</sequence>
	</complexType>

	<complexType name="attribute">
		<attribute name="value" type="string"></attribute>
		<attribute name="condition" type="string"/>
	</complexType>

	<complexType name="equipable">
		<sequence>
			<element name="slot" type="Q1:slot" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="slot">
		<attribute name="name" type="string"></attribute>
	</complexType>

	<complexType name="damage">
		<attribute name="type" type="string" />
	</complexType>

	<complexType name="susceptibility">
		<attribute name="type" type="string" />
		<attribute name="value" type="decimal" />
	</complexType>

	<complexType name="statusresist">
		<attribute name="type" type="string" />
		<attribute name="value" type="decimal" />
		<attribute name="slots" type="string" />
	</complexType>
</schema>

=== PolanieOnLine/PolanieOnLine/data/conf/items/jewellery.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="stendhal ../items.xsd ">

	<item name="ametyst">
		<type class="jewellery" subclass="amethyst" tileid="-1"/>
		<description>Oto ametyst, cenny klejnot.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="500"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>
	
	<item name="szmaragd">
		<type class="jewellery" subclass="emerald" tileid="-1"/>
		<description>Oto szmaragd, cenny klejnot.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="200"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="szafir">
		<type class="jewellery" subclass="sapphire" tileid="-1"/>
		<description>Oto szafir, cenny klejnot.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="400"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="rubin">
		<type class="jewellery" subclass="carbuncle" tileid="-1"/>
		<description>Oto rubin, cenny klejnot.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="600"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="obsydian">
		<type class="jewellery" subclass="obsidian" tileid="-1"/>
		<description>Oto obsydian, znany jako szkło magmowe, ponieważ lawa gdy zastyga przyjmuje taki wygląd.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="1000"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="diament">
		<type class="jewellery" subclass="diamond" tileid="-1"/>
		<description>Oto diament. To nie tylko piękny klejnot ale i najtwardszy materiał.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="800"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="czarna perła">
		<type class="jewellery" subclass="blackpearl" tileid="-1"/>
		<description>Oto czarna perła, mimo iż jest czarna, cała lśni.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="100"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="kryształ diamentu">
		<type class="jewellery" subclass="diamond_crystal" tileid="-1"/>
		<description>Oto kryształ diamentu, cenny nieoszlifowany klejnot.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="267"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="kryształ ametystu">
		<type class="jewellery" subclass="amethyst_crystal" tileid="-1"/>
		<description>Oto kryształ ametystu, cenny nieoszlifowany klejnot.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="267"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="kryształ szmaragdu">
		<type class="jewellery" subclass="emerald_crystal" tileid="-1"/>
		<description>Oto kryształ szmaragdu, cenny nieoszlifowany klejnot.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="267"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="kryształ szafiru">
		<type class="jewellery" subclass="sapphire_crystal" tileid="-1"/>
		<description>Oto kryształ szafiru, cenny nieoszlifowany klejnot.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="267"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="kryształ rubinu">
		<type class="jewellery" subclass="carbuncle_crystal" tileid="-1"/>
		<description>Oto kryształ rubinu, cenny nieoszlifowany klejnot.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="267"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="kryształ obsydianu">
		<type class="jewellery" subclass="obsidian_crystal" tileid="-1"/>
		<description>Oto kryształ obsydianu, cenny nieoszlifowany klejnot.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="267"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="kryształ ciemnolitu">
		<type class="jewellery" subclass="nocturium_crystal" tileid="-1"/>
		<description>Oto kryształ ciemnolitu, łączący kamień światłości z mrokiem. Druga strona wręcz hipnotyzuje.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="klejnot ciemnolitu">
		<type class="jewellery" subclass="nocturium_gem" tileid="-1"/>
		<description>Oto klejnot ciemnolitu. Gdy się przypatrzysz to wewnątrz klejnotu jakby padał deszcz.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>
</items>

=== PolanieOnLine/PolanieOnLine/data/conf/items/boxes.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="stendhal ../items.xsd ">

	<item name="prezent">
		<type class="box" subclass="present" tileid="-1"/>
		<description>Oto prezent. Otwórz go.</description>
		<implementation class-name="games.stendhal.server.entity.item.Present"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="koszyk">
		<type class="box" subclass="basket" tileid="-1"/>
		<description>Oto koszyk. Spójrz do niego.</description>
		<implementation class-name="games.stendhal.server.entity.item.Basket"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="skarpeta">
		<type class="box" subclass="stocking" tileid="-1"/>
		<description>Oto skarpeta. Spójrz do środka.</description>
		<implementation class-name="games.stendhal.server.entity.item.Stocking"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="100"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="skrzynka">
		<type class="box" subclass="skrzynka" tileid="-1"/>
		<description>Oto skrzynka. Otwórz ją.</description>
		<implementation class-name="games.stendhal.server.entity.item.Present"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="brązowa skrzynia">
		<type class="box" subclass="brazowa_skrzynia" tileid="-1"/>
		<description>Oto brązowa skrzynia. Otwórz ją.</description>
		<implementation class-name="games.stendhal.server.entity.item.BrazowaSkrzynia"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
		</equipable>
	</item>

	<item name="srebrna skrzynia">
		<type class="box" subclass="srebrna_skrzynia" tileid="-1"/>
		<description>Oto srebrna skrzynia. Otwórz ją.</description>
		<implementation class-name="games.stendhal.server.entity.item.SrebrnaSkrzynia"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
		</equipable>
	</item>

	<item name="złota skrzynia">
		<type class="box" subclass="zlota_skrzynia" tileid="-1"/>
		<description>Oto złota skrzynia. Otwórz ją.</description>
		<implementation class-name="games.stendhal.server.entity.item.ZlotaSkrzynia"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
		</equipable>
	</item>

	<item name="skrzynia Areny Wyzwań">
		<type class="box" subclass="zlota_skrzynia" tileid="-1"/>
		<description>Oto nagroda zdobyta na Arenie Wyzwań. Otwórz ją aby otrzymać wyposażenie.</description>
		<implementation class-name="games.stendhal.server.entity.item.ChallengeArenaRewardChest"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
		</equipable>
	</item>
	<item name="skrzynia myśliwego">
		<type class="box" subclass="zlota_skrzynia" tileid="-1"/>
		<description>Oto Skrzynia Myśliwego zdobyta za polowanie u Janisława. Nagroda zależy od trudności i poziomu w chwili ukończenia zadania.</description>
		<implementation class-name="games.stendhal.server.entity.item.HuntingRewardChest"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
		</equipable>
	</item>
</items>

=== PolanieOnLine/PolanieOnLine/data/conf/items/monety.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">

	<item name="miedziaki">
		<type class="monety" subclass="miedziaki" tileid="-1"/>
		<description>Oto miedziaki. Podstawowy środek płatniczy najniższych klas społecznych.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="money"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="talary">
		<type class="monety" subclass="talary" tileid="-1"/>
		<description>Oto srebrne talary. Podstawowy środek płatniczy średnich klas społecznych.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
		</attributes>
		<weight value="0.01"/>
		<value value="100"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="money"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="dukaty">
		<type class="monety" subclass="dukaty" tileid="-1"/>
		<description>Oto złote dukaty. Środek płatniczy najwyżych klas społecznych.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
		</attributes>
		<weight value="0.01"/>
		<value value="10000"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="money"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>
</items>

=== PolanieOnLine/PolanieOnLine/data/conf/items/pas.xml
<?xml version="1.0" encoding="UTF-8" ?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">

	<item name="skórzany pas">
		<type class="pas" subclass="zwykly_skorzany_pas" tileid="-1"/>
		<description>Oto zwykły skórzany pas. Skąd pochodzi ta skóra?</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="1"/>
		</attributes>
		<weight value="1.0"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>

	<item name="wzmocniony skórzany pas">
		<type class="pas" subclass="wzmocniony_skorzany_pas" tileid="-1"/>
		<description>Oto wzmocniony skórzany pas. Co za wytrzymały materiał!</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="3"/>
		</attributes>
		<weight value="1.0"/>
		<value value="3"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>

	<item name="kolczany pas">
		<type class="pas" subclass="kolczany_pas" tileid="-1"/>
		<description>Oto kolczany pas.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="4"/>
		</attributes>
		<weight value="1.0"/>
		<value value="4"/>
		<susceptibility type="ice" value="1.11"/>
		<susceptibility type="fire" value="1.11"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>

	<item name="karmazynowy pas">
		<type class="pas" subclass="karmazynowy_pas" tileid="-1"/>
		<description>Oto karmazynowy pas. Jego klejnot daje ci większą ochornę.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="5"/>
		</attributes>
		<weight value="1.0"/>
		<value value="5"/>
		<susceptibility type="fire" value="0.91"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>

	<item name="złoty kolczany pas">
		<type class="pas" subclass="zloty_kolczany_pas" tileid="-1"/>
		<description>Oto złoty kolczany pas.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="6"/>
		</attributes>
		<weight value="1.0"/>
		<value value="6"/>
		<susceptibility type="light" value="0.91"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>

	<item name="pas elficki">
		<type class="pas" subclass="elficki_pas_z_rubinem" tileid="-1"/>
		<description>Oto pas elficki z rubinem. Od tego rubinu czuć jakąś pradawną magie.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="7"/>
		</attributes>
		<weight value="1.0"/>
		<value value="7"/>
		<susceptibility type="nature" value="0.91"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>

	<item name="pas zbójecki">
		<type class="pas" subclass="pas_zbojecki" tileid="-1"/>
		<description>Oto pas zbójecki. Idealny dla górala.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="8"/>
		</attributes>
		<weight value="1.0"/>
		<value value="8"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>

	<item name="pas krasnoludzki">
		<type class="pas" subclass="krasnoludzki_pas" tileid="-1"/>
		<description>Oto pas krasnoludzki. Został wykonany z porządnego materiału.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="9"/>
		</attributes>
		<weight value="1.0"/>
		<value value="9"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>

	<item name="pas wampirzy">
		<type class="pas" subclass="wampirzy_pas" tileid="-1"/>
		<description>Oto pas wampirzy.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="10"/>
		</attributes>
		<weight value="1.0"/>
		<value value="10"/>
		<susceptibility type="ice" value="0.91"/>
		<susceptibility type="fire" value="0.91"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>

	<item name="pas olbrzymi">
		<type class="pas" subclass="olbrzymi_pas" tileid="-1"/>
		<description>Oto pas olbrzymi. Znane jest jedynie pochodzenie tego pasa - pochodzi ono od gigantów i same rozmiary tego pasa są ogromne.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="11"/>
		</attributes>
		<weight value="1.0"/>
		<value value="11"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>

	<item name="złoty pas">
		<type class="pas" subclass="zloty_pas" tileid="-1"/>
		<description>Oto złoty pas.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="12"/>
		</attributes>
		<weight value="1.0"/>
		<value value="12"/>
		<susceptibility type="dark" value="1.11"/>
		<susceptibility type="light" value="0.91"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>

	<item name="czarny pas">
		<type class="pas" subclass="czarny_pas" tileid="-1"/>
		<description>Oto czarny pas.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="13"/>
		</attributes>
		<weight value="1.0"/>
		<value value="13"/>
		<susceptibility type="dark" value="0.91"/>
		<susceptibility type="light" value="1.11"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>

	<item name="pas z mithrilu">
		<type class="pas" subclass="pas_z_mithrilu" tileid="-1"/>
		<description>Oto pas z mithrilu.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<def value="14"/>
		</attributes>
		<weight value="1.0"/>
		<value value="14"/>
		<susceptibility type="dark" value="1.11"/>
		<susceptibility type="light" value="0.91"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="pas"/>
		</equipable>
	</item>
</items>
