=== PolanieOnLine/PolanieOnLine/data/conf/items.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">

	<element name="items" type="Q1:itemGroup"></element>

	<complexType name="itemGroup">
		<sequence>
			<element name="item" type="Q1:itemType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<simpleType name="tooltipCategory">
		<restriction base="string">
			<enumeration value="weapon"/>
			<enumeration value="armour"/>
			<enumeration value="accessory"/>
			<enumeration value="other"/>
		</restriction>
	</simpleType>

	<complexType name="itemType">
		<sequence>
			<element name="type" type="Q1:typeType" />
			<element name="description" type="string"></element>
			<element name="implementation" type="Q1:implementation"></element>
			<element name="unattainable" type="anyType" minOccurs="0" maxOccurs="1"></element>
			<element name="behavior" type="Q1:behavior" minOccurs="0" maxOccurs="1"></element>
			<element name="attributes" type="Q1:attributes"></element>
			<element name="weight" type="Q1:attribute" minOccurs="0" maxOccurs="1" />
			<element name="value" type="Q1:attribute" minOccurs="0" maxOccurs="1" />
			<element name="preview" type="string" minOccurs="0" maxOccurs="1" />
			<element name="susceptibility" type="Q1:susceptibility" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="equipable" type="Q1:equipable"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="condition" type="string"></attribute>
		<attribute name="rarity-enabled" type="boolean"></attribute>
		<attribute name="rarity-profile" type="string"></attribute>
		<attribute name="tooltip-category" type="Q1:tooltipCategory"></attribute>
	</complexType>

	<complexType name="typeType">
		<attribute name="class" type="string"></attribute>
		<attribute name="subclass" type="string"></attribute>
		<attribute name="tileid" type="int"></attribute>
	</complexType>

	<complexType name="implementation">
		<attribute name="class-name" type="string"></attribute>
	</complexType>
	
	<complexType name="behavior">
		<sequence>
			<element name="parameter" type="Q1:pair" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="class-name" type="string"/>
	</complexType>
	
	<complexType name="pair">
		<attribute name="name" type="string"/>
		<attribute name="value" type="string"/>
	</complexType>

	<complexType name="attributes">
		<sequence>
			<element name="itemdata" type="Q1:attribute" minOccurs="0"/>
			<element name="atk" type="Q1:attribute" minOccurs="0"/>
			<element name="ratk" type="Q1:attribute" minOccurs="0"/>
			<element name="damage_min" type="Q1:attribute" minOccurs="0"/>
			<element name="damage_max" type="Q1:attribute" minOccurs="0"/>
			<element name="def" type="Q1:attribute" minOccurs="0"/>
			<element name="immunization" type="Q1:attribute" minOccurs="0"/>
			<element name="amount" type="Q1:attribute" minOccurs="0" maxOccurs="unbounded"/>
			<element name="frequency" type="Q1:attribute" minOccurs="0" maxOccurs="unbounded"/>
			<element name="range" type="Q1:attribute" minOccurs="0"/>
			<element name="quantity" type="Q1:attribute" minOccurs="0"/>
			<element name="max_quantity" type="Q1:attribute" minOccurs="0"/>
			<element name="regen" type="Q1:attribute" minOccurs="0" maxOccurs="unbounded"/>
			<element name="lifesteal" type="Q1:attribute" minOccurs="0"/>
			<element name="parry_chance" type="Q1:attribute" minOccurs="0"/>
			<element name="armor_penetration" type="Q1:attribute" minOccurs="0"/>
			<element name="critical_damage_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="bleed_on_hit" type="Q1:attribute" minOccurs="0"/>
			<element name="execute_damage" type="Q1:attribute" minOccurs="0"/>
			<element name="poison_on_hit" type="Q1:attribute" minOccurs="0"/>
			<element name="distance_damage" type="Q1:attribute" minOccurs="0"/>
			<element name="flat_attack_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="flat_defense_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_poisoned" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_bleeding" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_shocked" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_confused" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_heavy" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_stunned" type="Q1:attribute" minOccurs="0"/>
			<element name="skill_atk" type="Q1:attribute" minOccurs="0"/>
			<element name="atk_additional_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="critical_additional_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="def_additional_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="rate_increase" type="Q1:attribute" minOccurs="0"/>
			<element name="critical_chance" type="Q1:attribute" minOccurs="0"/>
			<element name="critical_bonus_reduction" type="Q1:attribute" minOccurs="0"/>
			<element name="out_of_combat_regen" type="Q1:attribute" minOccurs="0"/>
			<element name="consumable_healing_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="physical_dodge_chance" type="Q1:attribute" minOccurs="0"/>
			<element name="low_health_damage_reduction" type="Q1:attribute" minOccurs="0"/>
			<element name="nightmare_chance" type="Q1:attribute" minOccurs="0"/>
			<element name="lifesteal_increase" type="Q1:attribute" minOccurs="0"/>
			<element name="health" type="Q1:attribute" minOccurs="0"/>
			<element name="persistent" type="Q1:attribute" minOccurs="0"/>
			<element name="life_support" type="Q1:attribute" minOccurs="0"/>
			<element name="slot_name" type="Q1:attribute" minOccurs="0"/>
			<element name="undroppableondeath" type="Q1:attribute" minOccurs="0"/>
			<element name="autobind" type="Q1:attribute" minOccurs="0"/>
			<element name="slot_size" type="Q1:attribute" minOccurs="0"/>
			<element name="menu" type="Q1:attribute" minOccurs="0"/>
			<element name="durability" type="Q1:attribute" minOccurs="0" maxOccurs="1"/>
			<element name="itemset" type="Q1:attribute" minOccurs="0"/>
			<element name="use_sound" type="Q1:attribute" minOccurs="0" maxOccurs="1"/>
		</sequence>
	</complexType>

	<complexType name="attribute">
		<attribute name="value" type="string"></attribute>
		<attribute name="condition" type="string"/>
	</complexType>

	<complexType name="equipable">
		<sequence>
			<element name="slot" type="Q1:slot" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="slot">
		<attribute name="name" type="string"></attribute>
	</complexType>

	<complexType name="damage">
		<attribute name="type" type="string" />
	</complexType>

	<complexType name="susceptibility">
		<attribute name="type" type="string" />
		<attribute name="value" type="decimal" />
	</complexType>

	<complexType name="statusresist">
		<attribute name="type" type="string" />
		<attribute name="value" type="decimal" />
		<attribute name="slots" type="string" />
	</complexType>
</schema>

=== PolanieOnLine/PolanieOnLine/data/conf/items/money.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">
	<item name="money">
		<type class="money" subclass="gold" tileid="-1"/>
		<description/>
		<implementation class-name="games.stendhal.server.entity.item.Money"/>
		<attributes>
			<quantity value="1"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="money"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<!-- START: Nowe rodzaje monet -->
	<item name="miedziaki">
		<type class="money" subclass="copper" tileid="-1"/>
		<description>Oto miedziaki. Podstawowy środek płatniczy najniższych klas społecznych.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="money"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="talary">
		<type class="money" subclass="silver" tileid="-1"/>
		<description>Oto srebrne talary. Podstawowy środek płatniczy średnich klas społecznych.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
		</attributes>
		<weight value="0.01"/>
		<value value="100"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="money"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="dukaty">
		<type class="money" subclass="gold" tileid="-1"/>
		<description>Oto złote dukaty. Środek płatniczy najwyżych klas społecznych.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
		</attributes>
		<weight value="0.01"/>
		<value value="10000"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="money"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>
	<!-- END: Nowe rodzaje monet -->
</items>

=== PolanieOnLine/PolanieOnLine/data/conf/items/herbs.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="stendhal ../items.xsd ">

	<item name="arandula">
		<type class="herb" subclass="arandula" tileid="-1"/>
		<description>Oto arandula. Zioło to ma właściwości lecznicze, jeśli wiesz jak je użyć.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="11"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="kokuda">
		<type class="herb" subclass="kokuda" tileid="-1"/>
		<description>Oto kokuda. Zioło to ma właściwości lecznicze, jeśli wiesz jak je użyć.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="225"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="kekik">
		<type class="herb" subclass="kekik" tileid="-1"/>
		<description>Oto kekik. Ziele to posiada właściwości lecznicze.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="27"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="mandragora">
		<type class="herb" subclass="mandragora" tileid="-1"/>
		<description>Oto korzeń mandragory. Ma właściwości lecznicze o ile wiesz jak je wydobyć.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="300"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="sclaria">
		<type class="herb" subclass="sclaria" tileid="-1"/>
		<description>Oto zioło sclaria. Ma łagodny zapach.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="27"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="pokrzywa">
		<type class="herb" subclass="pokrzywa" tileid="-1"/>
		<description>Oto pokrzywa. Możesz jej używać do robienia wywarów i naparów.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="mięta">
		<type class="herb" subclass="mint" tileid="-1"/>
		<description>Oto liście mięty. Możesz ich używać do robienia naparów.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="babka lekarska">
		<type class="herb" subclass="babka_lekarska" tileid="-1"/>
		<description>Oto babka lekarska. Jeśli wiesz jak jej użyć możesz uleczyć rany.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>
	<item name="mech renifera">
		<type class="herb" subclass="reindeer_moss" tileid="-1"/>
		<description>Oto mech renifera, który rosnie tylko w okolicach Semos. Jest całkiem delikatny dla reniferów, ale strasznie gorzki dla ludzi.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item" />
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
			<autobind value=""/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
		</equipable>
	</item>
</items>

=== PolanieOnLine/PolanieOnLine/data/conf/items/special.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="stendhal ../items.xsd ">

	<item name="talizman szczęścia">
		<type class="special" subclass="lucky_charm" tileid="-1"/>
		<description>Oto talizman szczęścia. Niektórzy uważają, że w jakiś sposób to im przynosi szczęście, natomiast inni uważają, że to przesąd.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
			<autobind value=""/>
		</attributes>
		<weight value="1.0"/>
		<value value="60"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="keyring"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="brosza z mithrilu">
		<type class="special" subclass="mithril_clasp" tileid="-1"/>
		<description>Oto brosza z mithrilu. Może służyć jako zapinka do płaszcza.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="1.0"/>
		<value value="120"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="mityczne jajo">
		<type class="special" subclass="mythical_egg" tileid="-1"/>
		<description>Oto mityczne jajo, ale nie wiesz po co jest.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="1.0"/>
		<value value="2500"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>


	<item name="magiczne skorupki">
		<type class="special" subclass="eggshells" tileid="-1"/>
		<description>Oto magiczne skorupki. Mają magiczne właściwości.</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="złoty żeton GMa">
		<type class="special" subclass="GM_tokend_gold2" tileid="-1"/>
		<description>Oto złoty żeton GMa. Czy to napawa cię dumą?</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<unattainable/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="srebrny żeton GMa">
		<type class="special" subclass="GM_tokend_silver" tileid="-1"/>
		<description>Oto srebrny żeton GMa. Czy to napawa cię dumą?</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<unattainable/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="brązowy żeton GMa">
		<type class="special" subclass="GM_tokend_bronze" tileid="-1"/>
		<description>Oto brązowy żeton GMa. Czy to napawa cię dumą?</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<unattainable/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="złoty puchar">
		<type class="special" subclass="puchar" tileid="-1"/>
		<description>Oto złoty puchar. Jest on dowodem na to, że zwyciężyłeś na jednym z wielu dużych uroczystości! :) Administracja gry życzy Ci dalszych sukcesów!</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
			<undroppableondeath value="1" />
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
		</equipable>
	</item>

	<item name="piłka">
		<type class="special" subclass="ball" tileid="-1"/>
		<description>Oto piłka. Znajdź kilku kumpli i zagrajcie sobie mecz.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
		</equipable>
	</item>

	<item name="płaszcz czerwonego kapturka">
		<type class="cloak" subclass="brightred_cloak" tileid="-1"/>
		<description>Oto płaszcz czerwonego kapturka. Pewna mała dziewczynka o imieniu Balbina o nim marzy.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes/>
		<weight value="1.0"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="cloak"/>
			<slot name="bag"/>
		</equipable>
	</item>

	<item name="czterolistna koniczyna">
		<type class="special" subclass="clover" tileid="-1"/>
		<description>Oto szczęśliwa czterolistna koniczyna. Jakie są szanse na znalezienie takiej!?</description>
		<implementation class-name="games.stendhal.server.entity.item.StackableItem"/>
		<attributes>
			<quantity value="1"/>
			<max_quantity value="2147483647"/>
		</attributes>
		<weight value="0.01"/>
		<value value="150"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="keyring"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>
</items>
