=== PolanieOnLine/PolanieOnLine/data/conf/items.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">

	<element name="items" type="Q1:itemGroup"></element>

	<complexType name="itemGroup">
		<sequence>
			<element name="item" type="Q1:itemType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<simpleType name="tooltipCategory">
		<restriction base="string">
			<enumeration value="weapon"/>
			<enumeration value="armour"/>
			<enumeration value="accessory"/>
			<enumeration value="other"/>
		</restriction>
	</simpleType>

	<complexType name="itemType">
		<sequence>
			<element name="type" type="Q1:typeType" />
			<element name="description" type="string"></element>
			<element name="implementation" type="Q1:implementation"></element>
			<element name="unattainable" type="anyType" minOccurs="0" maxOccurs="1"></element>
			<element name="behavior" type="Q1:behavior" minOccurs="0" maxOccurs="1"></element>
			<element name="attributes" type="Q1:attributes"></element>
			<element name="weight" type="Q1:attribute" minOccurs="0" maxOccurs="1" />
			<element name="value" type="Q1:attribute" minOccurs="0" maxOccurs="1" />
			<element name="preview" type="string" minOccurs="0" maxOccurs="1" />
			<element name="susceptibility" type="Q1:susceptibility" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="equipable" type="Q1:equipable"></element>
		</sequence>
		<attribute name="name" type="string" use="required"></attribute>
		<attribute name="condition" type="string"></attribute>
		<attribute name="rarity-enabled" type="boolean"></attribute>
		<attribute name="rarity-profile" type="string"></attribute>
		<attribute name="tooltip-category" type="Q1:tooltipCategory"></attribute>
	</complexType>

	<complexType name="typeType">
		<attribute name="class" type="string"></attribute>
		<attribute name="subclass" type="string"></attribute>
		<attribute name="tileid" type="int"></attribute>
	</complexType>

	<complexType name="implementation">
		<attribute name="class-name" type="string"></attribute>
	</complexType>
	
	<complexType name="behavior">
		<sequence>
			<element name="parameter" type="Q1:pair" minOccurs="0" maxOccurs="unbounded"/>
		</sequence>
		<attribute name="class-name" type="string"/>
	</complexType>
	
	<complexType name="pair">
		<attribute name="name" type="string"/>
		<attribute name="value" type="string"/>
	</complexType>

	<complexType name="attributes">
		<sequence>
			<element name="itemdata" type="Q1:attribute" minOccurs="0"/>
			<element name="atk" type="Q1:attribute" minOccurs="0"/>
			<element name="ratk" type="Q1:attribute" minOccurs="0"/>
			<element name="damage_min" type="Q1:attribute" minOccurs="0"/>
			<element name="damage_max" type="Q1:attribute" minOccurs="0"/>
			<element name="def" type="Q1:attribute" minOccurs="0"/>
			<element name="immunization" type="Q1:attribute" minOccurs="0"/>
			<element name="amount" type="Q1:attribute" minOccurs="0" maxOccurs="unbounded"/>
			<element name="frequency" type="Q1:attribute" minOccurs="0" maxOccurs="unbounded"/>
			<element name="range" type="Q1:attribute" minOccurs="0"/>
			<element name="quantity" type="Q1:attribute" minOccurs="0"/>
			<element name="max_quantity" type="Q1:attribute" minOccurs="0"/>
			<element name="regen" type="Q1:attribute" minOccurs="0" maxOccurs="unbounded"/>
			<element name="lifesteal" type="Q1:attribute" minOccurs="0"/>
			<element name="parry_chance" type="Q1:attribute" minOccurs="0"/>
			<element name="armor_penetration" type="Q1:attribute" minOccurs="0"/>
			<element name="critical_damage_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="bleed_on_hit" type="Q1:attribute" minOccurs="0"/>
			<element name="execute_damage" type="Q1:attribute" minOccurs="0"/>
			<element name="poison_on_hit" type="Q1:attribute" minOccurs="0"/>
			<element name="distance_damage" type="Q1:attribute" minOccurs="0"/>
			<element name="flat_attack_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="flat_defense_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_poisoned" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_bleeding" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_shocked" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_confused" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_heavy" type="Q1:attribute" minOccurs="0"/>
			<element name="resist_stunned" type="Q1:attribute" minOccurs="0"/>
			<element name="skill_atk" type="Q1:attribute" minOccurs="0"/>
			<element name="atk_additional_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="critical_additional_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="def_additional_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="rate_increase" type="Q1:attribute" minOccurs="0"/>
			<element name="critical_chance" type="Q1:attribute" minOccurs="0"/>
			<element name="critical_bonus_reduction" type="Q1:attribute" minOccurs="0"/>
			<element name="out_of_combat_regen" type="Q1:attribute" minOccurs="0"/>
			<element name="consumable_healing_bonus" type="Q1:attribute" minOccurs="0"/>
			<element name="physical_dodge_chance" type="Q1:attribute" minOccurs="0"/>
			<element name="low_health_damage_reduction" type="Q1:attribute" minOccurs="0"/>
			<element name="nightmare_chance" type="Q1:attribute" minOccurs="0"/>
			<element name="lifesteal_increase" type="Q1:attribute" minOccurs="0"/>
			<element name="health" type="Q1:attribute" minOccurs="0"/>
			<element name="persistent" type="Q1:attribute" minOccurs="0"/>
			<element name="life_support" type="Q1:attribute" minOccurs="0"/>
			<element name="slot_name" type="Q1:attribute" minOccurs="0"/>
			<element name="undroppableondeath" type="Q1:attribute" minOccurs="0"/>
			<element name="autobind" type="Q1:attribute" minOccurs="0"/>
			<element name="slot_size" type="Q1:attribute" minOccurs="0"/>
			<element name="menu" type="Q1:attribute" minOccurs="0"/>
			<element name="durability" type="Q1:attribute" minOccurs="0" maxOccurs="1"/>
			<element name="itemset" type="Q1:attribute" minOccurs="0"/>
			<element name="use_sound" type="Q1:attribute" minOccurs="0" maxOccurs="1"/>
		</sequence>
	</complexType>

	<complexType name="attribute">
		<attribute name="value" type="string"></attribute>
		<attribute name="condition" type="string"/>
	</complexType>

	<complexType name="equipable">
		<sequence>
			<element name="slot" type="Q1:slot" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="slot">
		<attribute name="name" type="string"></attribute>
	</complexType>

	<complexType name="damage">
		<attribute name="type" type="string" />
	</complexType>

	<complexType name="susceptibility">
		<attribute name="type" type="string" />
		<attribute name="value" type="decimal" />
	</complexType>

	<complexType name="statusresist">
		<attribute name="type" type="string" />
		<attribute name="value" type="decimal" />
		<attribute name="slots" type="string" />
	</complexType>
</schema>

=== PolanieOnLine/PolanieOnLine/data/conf/items/documents.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">

	<item name="karteczka">
		<type class="documents" subclass="paper" tileid="-1"/>
		<description>Widzisz karteczkę.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="kupon">
		<type class="documents" subclass="coupon" tileid="-1"/>
		<description>Widzisz kupon.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="koperta zaklejona">
		<type class="documents" subclass="closed_envelope" tileid="-1"/>
		<description/>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="koperta otwarta">
		<type class="documents" subclass="opened_envelope" tileid="-1"/>
		<description/>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="koperta zalakowana">
		<type class="documents" subclass="sealed_envelope" tileid="-1"/>
		<description/>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="koperta ze złamaną pieczęcią">
		<type class="documents" subclass="unsealed_envelope" tileid="-1"/>
		<description/>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="licencja na zabijanie">
		<type class="documents" subclass="license" tileid="-1"/>
		<description>Oto licencja na zabijanie. Odpowiednio użyta otworzy wiele drzwi.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<quantity value="1"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="keyring"/>
		</equipable>
	</item>

	<item name="mapa">
		<type class="documents" subclass="mapwithgrid" tileid="-1"/>
		<description/>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
		</equipable>
	</item>

	<item name="zwój papieru">
		<type class="documents" subclass="scroll" tileid="-1"/>
		<description>Oto zwój papieru.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<quantity value="1"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<item name="lodowy zwój">
		<type class="documents" subclass="ice_scroll" tileid="-1"/>
		<description>Oto lodowy zwój pokryty płatkami śniegu. Możesz poczuć bijącą z niego zimną aurę.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<quantity value="1"/>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>

	<!--<item name="receptura">
		<type class="documents" subclass="recipe" tileid="-1"/>
		<description>Oto receptura gotowa do dostarczenia dla Imorgena. Znajdują się na niej nazwy składników do potężnej mikstury przeciwko wilkołakom. </description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item>-->

	<!--<item name="liścik do aptekarza">
    <type class="documents" subclass="paper" tileid="-1"/>
		<description>Oto liścik do aptekarza. To jest rekomendacja od Klaasa.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="lhand" />
			<slot name="rhand" />
		</equipable>
	</item>-->
	
	<item name="wyniki badań">
    <type class="documents" subclass="paper" tileid="-1"/>
		<description>Oto wyniki badań od Dr. Wojciecha. Trzeba je zanieść do drugiego weterynarza jakim jest Dr. Feelgood!</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="0.01"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="lhand" />
			<slot name="rhand" />
		</equipable>
	</item>
</items>

=== PolanieOnLine/PolanieOnLine/data/conf/items/animationrings.xml
<?xml version="1.0" encoding="UTF-8"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../items.xsd ">

	<item name="srebrny pierścień">
    <type class="animation_ring" subclass="silver_ring" tileid="-1"/>
    <description>Oto srebrny pierścień.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <atk value="2"/>
      <def value="2"/>
    </attributes>
    <weight value="0.1"/>
    <value value="323032"/>
    <susceptibility type="dark" value="0.83"/>
    <susceptibility type="light" value="1.11"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="finger"/>
      <slot name="fingerb"/>
      <slot name="keyring"/>
    </equipable>
  </item>

	<item name="złoty pierścień">
    <type class="animation_ring" subclass="golden_ring" tileid="-1"/>
    <description>Oto złoty pierścień.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <atk value="3"/>
      <def value="3"/>
    </attributes>
    <weight value="0.1"/>
    <value value="323032"/>
    <susceptibility type="dark" value="1.11"/>
    <susceptibility type="light" value="0.83"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="finger"/>
      <slot name="fingerb"/>
      <slot name="keyring"/>
    </equipable>
  </item>

  <item name="pierścień z mithrilu">
    <type class="animation_ring" subclass="mithril_ring" tileid="-1"/>
    <description>Oto pierścień z mithrilu. Został wykonany z bardzo wysoko-jakościowego materiału.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <atk value="4"/>
      <def value="5"/>
    </attributes>
    <weight value="0.1"/>
    <value value="323032"/>
    <susceptibility type="dark" value="1.11"/>
    <susceptibility type="light" value="0.83"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="finger"/>
      <slot name="fingerb"/>
      <slot name="keyring"/>
    </equipable>
  </item>

  <item name="czarny pierścień">
    <type class="ring" subclass="black_ring" tileid="-1"/>
    <description>Oto czarny pierścień. Czujesz wielką siłę kiedy go nosisz.</description>
    <implementation class-name="games.stendhal.server.entity.item.Item"/>
    <attributes>
      <atk value="5"/>
      <def value="4"/>
    </attributes>
    <weight value="0.1"/>
    <value value="123032"/>
    <susceptibility type="dark" value="0.83"/>
    <susceptibility type="light" value="1.11"/>
    <equipable>
      <slot name="ground"/>
      <slot name="content"/>
      <slot name="bag"/>
      <slot name="trade"/>
      <slot name="finger"/>
      <slot name="fingerb"/>
      <slot name="keyring"/>
    </equipable>
  </item>
</items>

=== PolanieOnLine/PolanieOnLine/data/conf/items/relics.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<items xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="stendhal ../items.xsd ">

	<!-- <item name="figurka aniołka" condition="stendhal.testserver">
		<type class="relic" subclass="angel_figurine" tileid="-1"/>
		<description>Oto świecąca figurka aniołka.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
			<quantity value="1"/>
		</attributes>
		<weight value="1.0"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="lhand"/>
			<slot name="rhand"/>
		</equipable>
	</item> -->

	<item name="pierścień z czaszką">
		<type class="relic" subclass="skull_ring" tileid="-1"/>
		<description>Oto pierścień z czaszką.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="1.0"/>
		<value value="250"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="finger"/>
			<slot name="keyring"/>
		</equipable>
	</item>

	<item name="amulet">
		<type class="relic" subclass="amulet" tileid="-1"/>
		<description/>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="1.0"/>
		<value value="800"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="keyring"/>
		</equipable>
	</item>

	<!-- <item name="ankh" condition="stendhal.testserver">
		<type class="relic" subclass="ankh" tileid="-1"/>
		<description>Oto tajemniczy symbol, który widziałeś w kraju piramid. Nie wiesz do czego służy.</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="1.0"/>
		<value value="1"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="keyring"/>
		</equipable>
	</item> -->

	<item name="złoty amulet">
		<type class="relic" subclass="golden_amulet" tileid="-1"/>
		<description>Oto złoty amulet. Ma przed czymś chronić?</description>
		<implementation class-name="games.stendhal.server.entity.item.Item"/>
		<attributes>
		</attributes>
		<weight value="1.0"/>
		<value value="1234"/>
		<equipable>
			<slot name="ground"/>
			<slot name="content"/>
			<slot name="bag"/>
			<slot name="trade"/>
			<slot name="neck"/>
		</equipable>
	</item>
</items>
